- .travis.yml
We only build the code and do some static analysis.
Fixes #14
> travis: Initial and basic support

- .travis.yml
- README.md
- hypervisor.go
- mock_hypervisor.go
- pod_test.go
- qemu.go
This PR adds a few pod unit tests as our first code coverage attempt.
It also enables travis unit testing and code coverage report.
> First pod unit tests

- agent.go
- hyperstart.go
- pod.go
- sshd.go
- virtc/main.go
- Add volume parameter to command line
- Fix comment formatting issues
- Check connection status every time start() is called
> Add "volume" parameter to command line and handle reconnection to the agent

- virtc/main.go
Add a parameter to command line to specify the initial command to run on pod containers.
It fixes issue #4
> Pass initial command to run on pod containers through virtc

- hyperstart_test.go
- nsenter_test.go
- qemu_test.go
- spawner_test.go
- Hyperstart unit testing (partially)
- NsEnter unit testing (fully)
- Spawner unit testing (fully)
- Qemu unit testing (partially)
> Add unit tests

- agent.go
- api.go
- hyperstart.go
- hyperstart_test.go
- hypervisor.go
- noop_agent.go
- nsenter_test.go
- pod.go
- pod_test.go
- qemu.go
- qemu_test.go
- spawner_test.go
- sshd.go
- virtc/main.go
Merging PRs #20, #25 and #26 from Sebastien.
> Sebastien PRs merge

- pod.go
- pod_test.go
Pod dir and files unit tested.
> More pod unit tests

- hyperstart.go
- pod.go
- qemu.go
- qemu_test.go
- virtc/main.go
> Fix comments related to PRs

- pod.go
- pod_test.go
This PR fixes the previous PR#21, relying on comments provided by @sameo
> pod: Fix containers statuses

- README.md
- hyperstart.go
The hyperstart daemon will mount the 9pfs shared directory specific
containers rootfs entry into the guest. Here we bind mount all container
bundle rootfs to the host shared_dir/pods/[podID]/[containerID].
This is how hyperstart will see all container bundles for a given pod
and mount it separately again in the guest.
> hyperstart: Bind mount container bundle rootfs

- README.md
- agent.go
- api.go
- container.go
- hyperstart.go
- hyperstart/hyperstart.go
- noop_agent.go
- pod.go
- sshd.go
- virtc/main.go
We don't want the enhanced locking and the higher level locking from PR #39.
> Cherry picking Sebastien's PR

- README.md
> README: Add the godoc link

- doc.go
- example_pod_run_test.go
A simple pod running example and a doc.go file to be expanded.
> doc: Add an initial overview and one example

- hypervisor_test.go
This PR fully implements hypervisor unit testing.
> hypervisor: Add unit testing

- mock_hypervisor_test.go
This PR fully covers the unit testing of the mock hypervisor.
> mock_hypervisor: Add unit testing

- noop_agent_test.go
This PR fully covers the unit testing of noop agent.
> noop_agent: Add unit testing

- syscall_test.go
This PR covers the unit testing of syscall.go file.
> syscall: Add unit testing

- api_test.go
- mock_hypervisor.go
- pod_test.go
This PR starts unit testing coverage for api.go.
> api: Add unit testing

- agent.go
- agent_test.go
This PR fully implement unit testing for agent.go.
> agent: Add unit testing

- api_test.go
- container.go
This PR increase the unit testing coverage for api.go.
It also fixes a bug in container.go.
> api: Add unit testing for container API

- filesystem_test.go
This PR starts unit testing coverage for the filesystem implementation of the storage interface.
> filesystem: Add unit testing

- hyperstart/hyperstart.go
- hyperstart/hyperstart_test.go
This PR enhances the hyperstart API, by allowing Clear Containers 2.1 (or any other consumer of this API) to be really independent from the hyperstart protocol. This means it won't need to be aware about hyperstart protocol anymore.
> hyperstart: Add new functions to the API

- api_test.go
- hyperstart/hyperstart_test.go
- hyperstart/mock/hyperstart.go
- hyperstart_test.go
- pod_test.go
This PR starts to cover hyperstart agent implementation. It also fixes some minor issues related to mock hyperstart and some unit tests.
> Cover hyperstart agent unit testing

- agent.go
- agent_test.go
- pod.go
- pod_test.go
This PR mainly increases unit testing coverage related to pod.go.
> Increase pod unit testing coverage

- README.md
And make it point to our master branch...
> README: Fix coveralls badge

- api.go
- cni.go
- cnm.go
- filesystem.go
- hack/virtc/main.go
- hyperstart/hyperstart.go
- hyperstart/hyperstart_test.go
- hyperstart/mock/hyperstart.go
- hypervisor.go
- logger/gloginterface/interface.go
- mock_hypervisor.go
- mock_hypervisor_test.go
- network.go
- network/cni/cni.go
- noop_network.go
- pod.go
- pod_test.go
- qemu.go
This PR starts the implementation of issue #2, that is the networking isolation for our pods.
> Implement network isolation

- .gitignore
Add .gitignore file to prevent git from tracking unwanted files.
> .gitignore: Ignore created binary and *.patch files

- Makefile
- api_test.go
- hack/virtc/README.md
- hack/virtc/main.go
- hyperstart.go
- hyperstart/hyperstart.go
- hyperstart/mock/hyperstart.go
- pause/Makefile
- pause/pause.c
- pod.go
- qemu.go
- qemu_test.go
Several changes to hyperstart API and pod lifecycle forced us to modify our library to continue to work properly.
Pause container issue #83.
> Update virtcontainers project to work with latest hyperstart changes

- network/cni/cni_test.go
- pod_test.go
> tests: Print err when failing to setup the tests

- api_test.go
- qemu.go
Those benchmarks measure the time it takes to create, start, and stop a pod.
Eventually, we should have start specific benchmarks, and stop ones.
> Add benchmarks

- .travis.yml
> ci: Send Travis notifications to Slack

- api.go
- api_test.go
- container.go
- hack/virtc/main.go
- pod.go
Some adjustments related to what can expect different runtimes, and particularly OCI runtime, needs to be made to get everything working as expected.
> Adapt virtcontainers to fit different runtime expectations

- pkg/oci/utils.go
- pkg/oci/utils_test.go
Through this patch, the OCI package provides a convenient way to convert
internal virtcontainers status to the expected OCI state defined in the
OCI specification.
> pkg: oci: Translate virtcontainers status to OCI state

- CONTRIBUTING.md
> CONTRIBUTING: Add contributions guidelines

- filesystem.go
Remove duplication in filesystem.createAllResources().
> filesystem: Remove duplication.

- container.go
Refactored a common preamble used by start(), stop(),
enter() and kill() into a helper function.
> container: Add helper function for boilerplate code.

- agent.go
- api.go
- api_test.go
- cc_proxy.go
- container.go
- hack/virtc/main.go
- hyperstart.go
- noop_agent.go
- noop_agent_test.go
- noop_proxy.go
- pod.go
- proxy.go
- sshd.go
The purpose of this PR is to bring the changes we will need to integrate very quickly the new proxy version. Once the proxy will be released, only very minor changes will be needed to get virtcontainers working with this new version.
> Anticipate changes introduced by new proxy version

- hyperstart.go
- network.go
Expected network has to be described to the agent running inside the
VM so as to set it up properly. Hyperstart agent implementation needs
to do that during the starting of the pod because network description
is passed through the STARTPOD command.
> hyperstart: Setup the network inside the VM

- hyperstart.go
Gateway parameter given to hyperstart was sometimes not filled
properly in case it was nil. After a specific check, we can be
sure the gateway value is proper.
With the same idea, the netMask needed to be processed from the
hexadecimal value because hyperstart expect it as an integer.
At last, we don't need NetMask field in the hyperstart structure
HyperNetIface because it is already contained into each structure
HyperIPAddress.
> hyperstart: Fix IP netmask and route gateway

- cnm.go
- hyperstart.go
- network.go
- pkg/oci/utils.go
- pkg/oci/utils_test.go
- qemu.go
- qemu_test.go
Through the enabling of the entire 3.0 stack, we have found some issues about virtcontainers that have to be fixed to get everything working as expected.
> Fix virtcontainers according to runtime 3.0 enabling

- Makefile
Nothing bad, just a couple of light touches on the Makefile.
> A couple of trivial Makefile fixes

- cc_proxy.go
- hyperstart.go
- proxy.go
This patch updates the cc-proxy implementation of the proxy, relying
on latest proxy changes (version 3.0).
> cc_proxy: Move to proxy v3.0

- .gitignore
- Use absolute ignore rules for single binaries
- Ignore objects files (pause.o wasn't ignored)
> gitignore: Update the .gitignore file

- README.md
This updates cleans a bit the README according to the latest version of virtcontainers library.
> virtcontainers: Update README.md

- hack/virtc/README.md
This PR cleans README.md according to the latest changes made to virtcontainers library.
> virtc: Update README.md

- .travis.yml
- Makefile
And have Travis verify that our Makefile works.
> Makefile: Do not build all vendor packages

- api_test.go
- network_test.go
- proxy_test.go
This PR adds more unit test coverage.
> virtcontainers: Improve unit testing

- hack/virtc/README.md
- hack/virtc/main.go
This PR makes the logging more consistent and modular for virtc.
It also adds some explanations about setting up the proxy (cc-proxy).
> virtc: Improve logging and documentation

- cc_proxy.go
Our payload will be marshalled by the proxy already.
> cc_proxy: Do not marshal twice

- api_test.go
- virtcontainers_test.go
This PR fixes issues preventing the benchmarks from being run properly.
> test: Fix benchmarks

- cc_shim.go
- cc_shim_test.go
- ci/ci-setup.sh
- container.go
- hack/virtc/README.md
- hack/virtc/main.go
- hyperstart.go
- noop_shim.go
- noop_shim_test.go
- pkg/oci/utils.go
- pkg/oci/utils_test.go
- pod.go
- shim.go
- shim/mock/shim.go
- shim_test.go
This PR basically introduces the notion of shim inside virtcontainers.
> shim: Add shim to virtcontainers

- .pullapprove.yml
- CONTRIBUTING.md
- OWNERS
- pkg/cni/OWNERS
> OWNERS: Add OWNERS files

- pod.go
- pod_test.go
GetContainer returns the container named by containerID (param)
> pod: Add function to get a specific container

- container.go
- container_test.go
Annotations returns the container's annotations
> container: Add function to get container's annotations

- pod.go
- pod_test.go
SetOrAddAnnotation is a function to set or add
annotations to a pod
> pod: add function to set or add annotations

- api.go
- pod.go
> api: Remove the session ending call

- qemu.go
> qemu: Enable virtio-net vhost by default

- hack/virtc/main.go
- hypervisor.go
- hypervisor_test.go
- pkg/oci/utils.go
- pkg/oci/utils_test.go
- qemu.go
- qemu_test.go
Offload that to the runtime, who's now supposed to call `AddKernelParam`.
> Remove Clear Containers specific kernel parameters

- .pullapprove.yml
- OWNERS
Add @dlespiau as an additional project approver.
Fixes #300.
> CI: Add additional project approver

- .pullapprove.yml
Add @amshinde as new approver to this project.
Fixes #306
> CI: Add additional approver

- .ci/ci-jobs.sh
- .ci/go-lint.sh
- Makefile
- filesystem.go
- hack/virtc/main.go
- hypervisor.go
- pkg/oci/utils.go
- pod_test.go
This PR takes care of fixing all the issues found by the gometalinter after we properly enabled it. It was enabled before this PR, but it was not taking into account the warnings that we want to care about.
> Enable properly gometalinter and fix found issues

- README.md
* Add missing APIs documentation
* Clear the networking documentation
* Document shim and proxy
> README: Updates and fixes

- Gopkg.lock
- vendor/github.com/01org/ciao/qemu/qemu.go
- vendor/github.com/01org/ciao/qemu/qemu_test.go
- vendor/github.com/kubernetes-incubator/cri-o/vendor.conf
> vendor: Pulling ciao realtime changes

- Gopkg.lock
- vendor/github.com/01org/ciao/packages.json
- vendor/github.com/01org/ciao/qemu/qemu.go
- vendor/github.com/01org/ciao/qemu/qemu_test.go
- vendor/github.com/01org/ciao/ssntp/README.md
- vendor/github.com/01org/ciao/ssntp/ssntp.go
- vendor/github.com/clearcontainers/proxy/README.md
- vendor/github.com/containernetworking/cni/CONVENTIONS.md
- vendor/github.com/containernetworking/cni/GOVERNANCE.md
- vendor/github.com/containernetworking/cni/README.md
- vendor/github.com/containernetworking/cni/SPEC.md
- vendor/github.com/kubernetes-incubator/cri-o/.travis.yml
- vendor/github.com/kubernetes-incubator/cri-o/Dockerfile
- vendor/github.com/kubernetes-incubator/cri-o/Makefile
- vendor/github.com/kubernetes-incubator/cri-o/README.md
- vendor/github.com/kubernetes-incubator/cri-o/pkg/annotations/annotations.go
- vendor/github.com/kubernetes-incubator/cri-o/vendor.conf
- vendor/github.com/opencontainers/runtime-spec/config-linux.md
- vendor/golang.org/x/crypto/curve25519/curve25519.go
- vendor/golang.org/x/crypto/ssh/client_auth.go
- vendor/golang.org/x/sys/unix/mkerrors.sh
- vendor/golang.org/x/sys/unix/syscall_solaris.go
- vendor/golang.org/x/sys/unix/zerrors_solaris_amd64.go
- vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
- vendor/golang.org/x/sys/unix/ztypes_solaris_amd64.go
We need the ciao qemu locking changes:
f12f43d Knobs: Modify the behaviour of the Mlock knob
> vendor: Updates

- NEWS
Added QEMU memory locking support
Shortlog:
3e350ab vendor: Updates
> 1.0.1 release

- .pullapprove.yml
- OWNERS
> OWNERS: Add James O. D. Hunt

- Gopkg.lock
- Gopkg.toml
- container.go
- device.go
- device_test.go
- hypervisor.go
- pkg/oci/utils.go
- pkg/oci/utils_test.go
- pkg/oci/utils_test_config.go
- pod.go
- pod_test.go
- qemu.go
- qemu_test.go
- vendor/github.com/go-ini/ini/.gitignore
- vendor/github.com/go-ini/ini/.travis.yml
- vendor/github.com/go-ini/ini/LICENSE
- vendor/github.com/go-ini/ini/Makefile
- vendor/github.com/go-ini/ini/README.md
- vendor/github.com/go-ini/ini/README_ZH.md
- vendor/github.com/go-ini/ini/error.go
- vendor/github.com/go-ini/ini/ini.go
- vendor/github.com/go-ini/ini/ini_test.go
- vendor/github.com/go-ini/ini/key.go
- vendor/github.com/go-ini/ini/key_test.go
- vendor/github.com/go-ini/ini/parser.go
- vendor/github.com/go-ini/ini/parser_test.go
- vendor/github.com/go-ini/ini/section.go
- vendor/github.com/go-ini/ini/section_test.go
- vendor/github.com/go-ini/ini/struct.go
- vendor/github.com/go-ini/ini/struct_test.go
This add support for passing in vfio devices to the VM.
Requires ciao PR to be merged first:
https://github.com/ciao-project/ciao/pull/1444
> Vfio passthrough

- README.md
VFIO device groups can now be passed with --device.
Describe the setup steps required.
> docs: Describe how vfio devices can be passed

- cni.go
- container.go
- device.go
- filesystem.go
- hook.go
- hyperstart.go
- network.go
- pod.go
- qemu.go
- shim.go
Switch to structured logging for parity with other system components.
Fixes #398.
> logging: Use structured logging

- qemu.go
Initialize and use the qmpLogger logger field instead
of using a global logger.
> qemu: Initialize qmp logger properly

- NEWS
Added SRIOV support
Added Multi-OS support
Removed Travis CI
Shortlog:
f08b6c1 hypervisor: Provide custom asset getter
ac2a937 asset: Extend asset support to firmware and hypervisor
fc5ae53 hypervisor: Add a private custom assets map
5504939 oci: Add asset annotations to the pod config
de377a9 pod: Select kernel and image assets from annotations
1d1c5f4 pkg: Add annotations package
ec2f2c3 network: Rename Endpoint interface methods.
6c31530 networking : Pass MTU information for physical network devices.
60b8c34 network: Skip setting MTU for physical interfaces.
ad92928 tests: Add test to check if interface is physical.
7ec762a tests: Add tests to check for Network Endpoint Types
96571ee tests: Modify tests to test for virtual endpoints.
dc715cf network: Add methods to attach and detach …
> 1.0.6 release

- device.go
Since vfio devices cannot be hotplugged currently, we
need to call atachDevices from pod.go.
We can avoid cold plugging block devices with this check for now.
Fixes https://github.com/clearcontainers/runtime/issues/802
> block: Skip cold-plugging block devices.

- .gitignore
Ignore .swp files created by vim
> gitignore: Add .swp files

- .gitignore
- container.go
- device.go
- device_test.go
- hypervisor.go
- network.go
- network_test.go
- qemu.go
- qemu_test.go
Changes for introducing vhost-user enabling to virtcontainers.
In future still need to add support for generic vhost-user-block devices and to test vhost-user SCSI end to end.
> vhostuser enabling

- pkg/oci/utils.go
We use a couple of relativley simple formulas to work out how much
RAM and how many vCPUs to allocate to the VM based on the
Resource request we are passed in.
Improve the comment on these calculations to make it clear which
way they round and if they impose a floor to the resulting value.
Fixes: #554
Signed-off-by: Graham Whaley <graham.whaley@intel.com>
> pkg/oci: Clarify resource calculation comment

- kata_agent.go
This commit constraints the OCI spec provided to the agent on
several point such as seccomp, hooks, network namespace and
Intel RDT.
Fixes #559
> kata_agent: Constraints the OCI spec

- api.go
- container.go
- pod.go
- pod_test.go
- virtcontainers_test.go
This pull request ensure the container pointers held by the `pod` structure are not duplicated. This is needed to avoid a container pointer modification not to be taken into account because the wrong pointer is used.
Fixes #588
> container: Fix container semantics

- api.go
- container.go
- pod.go
- pod_test.go
This pull request globally cleans up a few things related to the pod and simplify a few functions in order to make the code easier and clearer.
> pod: Simplify and cleanup the pod

- network.go
Fix errors detected by `.ci/go-lint.sh`.
Fixes #648.
> network: Fix lint errors

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/containerd/cri-containerd/pkg/annotations/annotations.go
- vendor/github.com/golang/protobuf/proto/discard.go
- vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
Since we are directly importing containerd package as a dependency,
this commit sets a constraint on the revision.
Fixes #658
> vendor: Constraint containerd vendoring
