containers/virtcontainers

hyperstart.go
hyperstart_test.go

- Get hyperstart more modular and using encoding/binary package
- Export some functions to allow sokt to rely on our code to communicate with hyperstart

Improve hyperstart and export functions

---

README.md
agent.go
hyperstart.go
noop_agent.go
pod.go
sshd.go
virtc/main.go

* We only support unix sockets
* `-vm-vcpus` is now `-cpus`
* `-vm-memory` is now `memory`
* Make all virtc socket virtc command line settings optional

Simplify hyperstart and virtc command line

---

syscall.go
virtc/main.go

* Add syscall.go for wrapping system calls. We define a "smart" bind mount there for now.
* Enable glog and urfave/cli at the same time, so that we can debug virtc

Preparation for bind mounting the pod containers rootfs

---

qemu.go
qemu_test.go

Qemu command line create some mount tag with an hardcoded "rootfs" name. This was an issue because the systemd process tries to mount a rootfs mount tag by default. We want our containers mount tags to have a different name. Also, this patch allows each mount tag to be different for each container.

Fix VM issue related to wrong mount tag "rootfs"

---

README.md

VirtContainers could be used to build a CRI implementation, but
it's not the project primary goal.

README: Clarify relationships with k8s CRI

---

agent.go
container.go
hyperstart.go
noop_agent.go
pod.go
sshd.go

We take a Pod argument whenever we want to touch a Pod, and
a Container when we need to reach a container within that pod.

agent: Simplify the interface

---

api.go
pod.go
pod_test.go

In order to simplify the pod code, we push the pod locking in api.go,
the only external virtcontainers API.

api: Coarse locking

---

api.go
virtc/main.go

To StatusContainer for both consistency and godoc compliance
sake.

api: Rename ContainerStatus

---

hyperstart/hyperstart_test.go
hyperstart/mock/hyperstart.go
hyperstart/mock/misc.go
hyperstart/mock/rand.go

Because we want virtcontainers to host the mock hyperstart code, this PR moves the code from cc-oci-runtime repository.
It fixes issue #40.

Move mock hyperstart from cc-oci-runtime

---

api.go
container.go
filesystem.go
pod.go
pod_test.go

We move all the pod resources (config, state) storage
implementation in filesystem.go and while doing so we
redefine the pod storage interface.
The new interface is more resource centric and tries to
be lower level than the previous one.
Fixes #48

filesystem: Redefine the pod storage interface

---

mock_hypervisor_test.go

This PR fixes a bug introduced by concurrent PRs already merged. The StartPod was blocking because a channel was expecting to send a message but it was never read.

hypervisor: Fix mock hypervisor unit testing

---

.travis.yml
README.md
api_test.go
example_pod_run_test.go
hack/virtc/README.md
hack/virtc/main.go
hyperstart.go
hyperstart/hyperstart_test.go

Moving to github.com/containers broke a few imports and URLs.

virtcontainers: Fix paths

---

hyperstart/hyperstart.go
hyperstart/hyperstart_test.go
hyperstart/mock/hyperstart.go

We're supposed to be able to receive an ack message after a destroypod.
The fact that we didn't was caused by our use of hyperstart as a daemon
(vs an init process) and some bugs introduced by that.
With those fixed, we have the destroypod ack message back.

hyperstart: Don't special-case destroypod

---

.travis.yml
hyperstart.go
hyperstart/hyperstart.go
hyperstart/hyperstart_test.go
hyperstart/mock/hyperstart.go

Hyperstart upstream changed fairly drastically, see:
https://github.com/hyperhq/runv/pull/388
with hardly any explanations. Trying to keep up with the changes...

hyperstart: Support upstream changes

---

hyperstart/hyperstart.go
hyperstart/hyperstart_test.go

There's a problem in reseting those sockets to nil when
CloseSockets() is called but other hyperstart methods are
being run in go routines. The methods in the goroutines
end up trying to dereference nil.
It's safer to just close the socket so the goroutines in
flight can still can Read() or Write() on them, which is
exit with io.EOF.
This trace is from killing the cc-shim process trying to
send a CTL message in the middle of tearing down the VM
(so CTL socket is closed):
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x4e0044]
goroutine 56 [running]:
panic(0x540220, 0xc4200100f0)
/home/damien/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/containers/virtcontainers/hyperstart.(*Hyperstart).writeCtlMess …

hyperstart: Don't reset the connections to nil in CloseSockets()

---

agent_test.go
api_test.go
filesystem_test.go
hypervisor_test.go
mock_hypervisor_test.go
noop_agent_test.go
nsenter_test.go
pod_test.go
qemu_test.go
spawner_test.go
syscall_test.go

We should pass non nil errors to Fatal().

unit: Log errors when they're not nil

---

.travis.yml
network/cni/cni.go
network/cni/cni_test.go

CNI package handling the usage of the CNI plugin was not covered by
any unit test until now. This patch aims to cover as much as possible
the unit testing of this cni package.
Furthermore, some minor changes have been brought to the cni package
itself in order to be able to test the package more easily.
Notice that we need to modify travis.yml to properly setup the
test environment.

network: cni: Add unit testing

---

.travis.yml

We introduced those "go get" recently with the PR #82, but we don't need them, so let's remove them.

travis: Don't install unneeded go packages

---

agent.go
api_test.go
cc_proxy.go
hack/virtc/README.md
hack/virtc/main.go
hyperstart.go
noop_agent.go
noop_agent_test.go
noop_proxy.go
pod.go
proxy.go
sshd.go

Virtcontainers reached a point where it needs to rely on the hyperstart proxy if we want to go further. This PR solves issue #85 by implementing two proxy interfaces, a raw hyperstart intended to communicate directly  with hyperstart, and a real proxy responsible to do the abstraction layer with the VM.

Implement proxy

---

hyperstart/hyperstart.go
hyperstart/hyperstart_test.go

This PR exposes low level functions to read/write hyperstart commands, this will be needed for the proxy to emulate a ctl fd for each client.

Low level hyperstart read/write

---

cc_proxy.go
network/cni/cni.go

Our cni package relies on libcni library and they recently updated one function we were using, thus we provide the fix for that.
Then, proxy API from cc-oci-runtime changed recently due to a global re-design, meaning it had to change the Client API too. Because we use this Client API to communicate with cc-proxy, we have to fix it to allow our build to pass.

Fix build due to recent dependencies changes

---

.travis.yml
README.md

coveralls was still pointing at our old repo.

travis: Re-enable code coverage

---

cc_proxy.go

Hopefully the first and only client API change before we tag 2.1.
References: https://github.com/01org/cc-oci-runtime/pull/595
--
Of course, this PR is going to fail and the related PR in the runtime isn't merged yet.

cc-proxy: Follow the latest API change

---

network.go
network/cni/cni.go
network/cni/cni_test.go

The package github.com/containernetworking/cni/pkg/types has been recently
modified and the Result structure has been moved to an interface. Instead,
two new packages cni/pkg/types/020 and cni/pkg/types/current have been added.
Those new packages provides some functions to convert the Result interface
into a 020.Result or current.Result structure.
Because we want to follow latest version, this commit modifies our cni and
virtcontainers packages so as to get current.Result structure.

Fix the build according to API changes from cni/pkg/types

---

hyperstart/hyperstart.go
hyperstart/hyperstart_test.go
hyperstart/multicast.go

Recent changes in hyperstart project introduced new commands, and particularly PROCESSASYNCEVENT which is returned on the CTL channel to return the exit code of a process running on a container.
This PR handles those changes by fixing "hyperstart" and "mock" packages in virtcontainers, and also by fixing virtcontainers itself.

Update hyperstart in virtcontainers to follow recent changes from hyperstart project

---

.travis.yml
api.go
cni.go
cnm.go
cnm_test.go
filesystem.go
hook.go
hook/mock/hook.go
hook_test.go
hypervisor.go
mock_hypervisor.go
mock_hypervisor_test.go
network.go
network_test.go
noop_network.go
pod.go
pod_test.go
qemu.go

This PR modifies the way the network interface was handled for the CNI implementation so that it can work for the CNM implementation. Then, it adds the OCI hooks handling, because we need to be able to handle those hooks for network setup. At last, it implements the CNM network interface.

CNM network implementation

---

.travis.yml
api.go
api_test.go
cni.go
cnm.go
network.go
noop_network.go
pod.go
test/cni/10-mynet.conf
test/cni/99-loopback.conf

We first needed to fix the way we were using the netns. Indeed, it is not safe to switch to a netns, but instead we should execute a block of code inside the specified namespace.
This allowed us to avoid netns confusion and mixing with CNI plugin, and we have been able to add a new unit test relying on CNI network.

Fix netns usage and improve network unit testing coverage

---

api.go
cni.go
cnm.go
network.go
noop_network.go
pod.go

We're mostly running a callback into a networking namespace, not
just joining a netns.

network: Rename join to run

---

pkg/oci/LICENSE
pkg/oci/utils.go
pkg/oci/utils_test.go
pkg/oci/utils_test_config.go

This is a package for converting an OCI configuration file (`config.json`) into virtcontainers `PodConfig` structure.
The single exported API is `PodConfig()` that takes a bundle path, a container ID, a console path and a runtime configuration structure as arguments.
The runtime configuration structure will come from e.g. http://github.com/clearcontainers/runtimeissues/25.

OCI utils package

---

cc_proxy.go
hack/virtc/main.go
pkg/oci/utils.go
pod.go
proxy.go

We want to be able to specify some proxy specific settings, like e.g. the proxy runtime socket path for our Clear Containers proxy implementation. Eventually, this will also include the proxy shim socket path.

Add a proxy configuration interface

---

api.go
hack/virtc/main.go
hyperstart.go
pod.go

In order to allow future performance savings with OCI runtime, this PR moves VM creation/deletion to CreatePod()/DeletePod(). It does the same for the network which is now created/removed from CreatePod()/DeletePod() too.

Move VM creation and network setup to CreatePod()

---

NEWS

Changed the CreatePod/StartPod logic
Added an OCI config file conversion package
Added initial benchmarks
Added more CNI network unit tests
Moved all non virtcontainers packages under pkg/
Fixed netns race conditions

0.5.0 release

---

api.go

When the move of the VM creation and network setup were done in a previous
pull request, the changes to RunPod() have not been done. This patch aims
to fix this.

api: Fix RunPod() according to changes to VM and network creation

---

container.go
pod.go
pod_test.go

Because we want to make the difference with a pod just created and a pod
already started and then stopped, we remove the paused state not used, and
we replace it with a stopped state.
This means that we can have now a pod and its containers in the following
states:
On Create():
- "" -> created
On Delete():
- created -> ""
- stopped -> ""
On Start():
- created -> running
- stopped -> running
On Stop():
- running -> stopped

pod: Change paused state to stopped state

---

container.go
filesystem.go
filesystem_test.go
hyperstart.go
pod.go

Until now, the Pod structure was keeping containers configurations but
it is not the right thing to do because we want to be able to access
containers through a handler kept by the Pod structure. That's why
this patch changes the containers configuration list to containers
handler list.

pod: Keep containers instead of containers configs in Pod structure

---

pkg/oci/utils.go
pkg/oci/utils_test.go

Because OCI specification does not have the concept of pod, we have
to match the container ID on the pod ID, and assign an arbitrary
value to the virtcontainers internal container ID. In that case,
we chose "0" but it could be anything else.

oci: Container ID should be considered as pod ID

---

agent.go
api.go
container.go
hyperstart.go
noop_agent.go
sshd.go

Because OCI spec needs to be able to send a signal with the kill command and because it is something generic (not only OCI will need to send signals to containers), this PR adds the way to send a signal to a running container.

Add KillContainer API

---

container.go
filesystem.go
filesystem_test.go
pod.go

This PR adds the Process structure so that any runtime implementation can update PID related to the started process on the container. Also it can retrieve the token necessary for the shim to connect the proxy.

Introduce Process structure to allow runtime to get useful info about the container's process

---

hyperstart.go

We were not returning an error in case the REMOVECONTAINER command called from
stopContainer() was getting an error from hyperstart agent. We thought it could
not work to call a REMOVECONTAINER after a KILLCONTAINER, but after further testing,
here is the real behavior of hyperstart v0.7.0:
KILLCONTAINER: calling this command on an existing container will always succeed,
even if no process is running inside the container. This means that several calls
to KILLCONTAINER commands won't hurt. Calling this on a non-existing container will
return an error.
REMOVECONTAINER: calling this command on an existing container with no remaining
process running inside the container will succeed. In case there a remaining process
still running, this command will fail and return an error. If the container …

Fix hyperstart agent implementation of stopContainer after performed testing

---

container.go
hyperstart.go
pod.go
pod_test.go

Any runtime implementation will have to check virtcontainers states so that
it can convert them to the expected states defined in the runtime specification.

Make virtcontainers states public

---

api.go
api_test.go
container.go

Runtime implementation needs more information and we provide those information by extending the ContainerStatus structure. Then this PR improve the way those statuses are handled in virtcontainers.

Extend and improve pod and containers status

---

pod.go

When a pod object was created, we were never assigning its state in case
this state was already existing.

pod: Fix pod state not saved

---

pkg/oci/utils_test_config.go

The rc4+ OCI specs has moved from a single array of
capabilities to an array of arrays.

oci: Fix unit tests

---

pkg/oci/utils.go
pkg/oci/utils_test.go

Because the container state can be updated from the runtime in case we
check if the process ID is running or not, we want to retrieve the state
of the container instead the state of the pod, in order to be accurate.

OCI package: Return container state instead of pod state

---

NEWS

Added pullapprove support
Added Slack integration
Added KillContainer API
Added networking documentation
Added a Process structure for describing container processes
Added a more complete pod and container status structure
Fixed hyperstart implementation for stopping containers
Shortlog:
5d01bc4 pkg: oci: Return container state instead of pod state
87433a3 CONTRIBUTING: Add contributions guidelines
1ced118 travis: Add go 1.8 to the test matrix
a12f01a oci: Fix unit tests
8055f58 documentation: Add network diagrams to README.md
55263ae pod: Fix pod state not saved
ad20d1e pkg: oci: Translate virtcontainers status to OCI state
103540c api: Remove hardcoded filesystem calls
8721a59 container: Add PID and RootFs to ContainerStatus structure
b208b12 state: Make virtcontainers states public …

0.6.0 release

---

pkg/hyperstart/mock/hyperstart.go

Instead of manually printing to stderr, use the built-in testing.Log(f)
functions to output debug messages when the test running is set up to be
verbose.

hyperstart/mock: Don't directly print to stderr

---

pod.go

Volumes.Set() and Sockets.Set() now construct the Error message rather
than hard-coding separator and expected field counts.

pod: Don't hard-code details in returned Errors.

---

pod.go

PodConfig.valid() was calling newAgent() but ignoring the return value.
Since the return value isn't needed, remove the call.

pod: Remove redundant call to newAgent().

---

pkg/oci/utils.go

If StatusToOCIState() receives too many status values, display them in
the returned error.

oci: return more error details.

---

cnm.go
network.go
network_test.go

createNetworkEndpoint() can be passed invalid arguments, so make it
return an error to handle these situations.

network: Make createNetworkEndpoint() return an error.

---

hypervisor.go
qemu.go
qemu_test.go

Setting HypervisorConfig.Debug will change the default set of kernel
parameters to enable debug (boot) output. It could also be used to
enable hypervisor debug where available.

hypervisor: Add Debug option to HypervisorConfig.

---

filesystem.go

The call that follows will detect if the file does/does not
exist.

filesystem: Remove unecessary calls to os.Stat().

---

pkg/oci/utils.go
pkg/oci/utils_test.go

This converts an OCI Process.Env slice into a vc.EnvVar one.
This is needed by https://github.com/clearcontainers/runtime/pull/53

oci: Add a EnvVar slice conversion API

---

container.go

Programs using virtcontainers library will sometimes need to get
the process related to a container in case they have retrieved this
container. Process being a private field in the container structure,
we have to create a new public function to return it.

container: Add public function to retrieve container process

---

agent.go
api.go
api_test.go
cc_proxy.go
container.go
hack/virtc/main.go
hyperstart.go
noop_agent.go
noop_agent_test.go
noop_proxy.go
pod.go
proxy.go
sshd.go

Every time a runtime wants to start a shim, it needs a URL to know where to connect to the proxy. Through this PR, virtcontainers provide the way to get this URL from the Pod handler.
Also, at the time a runtime loads the proxy configuration, it will provide virtcontainers a URL that has to be parsed properly to know how to connect to the proxy. This PR also handles this.

Deal with URLs related to proxy

---

syscall.go

Don't discard the original error object as it contains essential
information for problem determination.

syscall: Return full error details.

---

pkg/oci/utils.go
pkg/oci/utils_test.go

OCI spec structure can be needed by the runtime in order to reuse
some data not stored inside PodConfig, but without unmarshalling
the JSON config file again.

pkg: oci: Return OCI spec structure from PodConfig()

---

pkg/oci/utils.go
pkg/oci/utils_test.go
pod.go

This PR provides a way for a virtcontainers' user to store/fetch private data through virtcontainers management.

Add pod annotations and update oci package to use them

---

cnm.go

There was an error in the code about the scan of interfaces found.
Indeed, this scan has to be performed inside the right netns to be
right. Otherwise, we are scanning the host interfaces.

cnm: Interface list has to be scanned from inside the network namespace

---

cc_proxy.go
hack/virtc/main.go
pod.go
qemu.go
qemu_test.go

We had no way to get logs printed inside the VM by our hyperstart
agent because we were missing several parts to be connected properly.
This patch enables the proxy to retrieve hyperstart logs coming from
inside the VM through a new console socket created by the hypervisor.
First it adds a new Console field to the PodConfig so as to be able
to share this socket path with other components such as proxy or
agent implementations.
Then we have to change systemd.unit parameter from "container.target"
to "cc-agent.target" because we need hyperstart output to be
redirected to the right console.
At last, the hypervisor implementation has to create a console socket
from the console path provided by the PodConfig.

pod: Enable pod console traces

---

cnm.go
cnm_test.go

When using CNM, we were not filling the results of each endpoint
for the Routes field. Now that we can rely on netlink package to
scan the routes inside the specified network namespace, we can
properly fill this field as expected.
As a comment, this is not needed in case of CNI because the plugin
takes care of this for us.

cnm: Fill endpoints results with routes

---

pkg/cni/cni_test.go

In order to follow more closely the CNI specification, some recent changes have been added to the CNI plugins so that they are not failing anymore in case we try to tear down a non existing network.
This patch fixes the unit test which was expecting to see a failure. Now, we are expecting a success in removing a network that we've never created before.
This PR fixes issue #166

pkg: cni: Fix unit testing after CNI plugins update

---

errors.go
hack/virtc/main.go

Ensure that all mandatory arguments are checked early.
Note that urfave/cli doesn't actually provide such a feature. The
approach taken attempts to avoid duplicated code by checking centrally,
rather than peppering checks on podID and containerID in lots of
functions.

virtc: Check mandatory command-line arguments.

---

.travis.yml
ci/ci-setup.sh
utils/virtcontainers-setup.sh

This new script helps any user or developer to get the proper
configuration in order to use and test virtcontainers library.
After this script is run, you should be able to use virtc CLI
and to run "go test" properly.

utils: Add a script setting up the environment for testing purpose

---

pause/pause.c

signal SIGKILL (as well as SIGSTOP) cannot be caught or ignored. And we
should remove this.

epause: remove SIGKILL handler

---

hyperstart.go
pkg/hyperstart/hyperstart.go
pkg/hyperstart/hyperstart_test.go
pkg/hyperstart/mock/hyperstart.go
pkg/hyperstart/multicast.go
pkg/hyperstart/types.go

This PR adds a new package to virtcontainers: pkg/hyperstart/api. This package duplicates/modify structures initially provided by github.com/hyperhq/runv/hyperstart/api/json, in order to prevent issues related to upstream modification of this package.
That way, the package provided provided by hyperstart can change according to the changes made to the binary, there is no way it can break our virtcontainers library. The clearcontainers/proxy will also rely on this new package.

Duplicate hyperstart API

---

.travis.yml

Travis didn't pass when running from a forked repo:
$ sudo env "PATH=$PATH" bash $GOPATH/src/github.com/containers/virtcontainers/ci/ci-setup.sh
bash: /home/travis/gopath/src/github.com/containers/virtcontainers/ci/ci-setup.sh: No such file or directory

travis: Add go_import_path directive

---

cni.go
container.go
hack/virtc/main.go
hook.go
hyperstart.go
pkg/hyperstart/multicast.go
pod.go
qemu.go

Glog causes some data race with project using our library and glog at the same time. For that reason, it is safer to move to logrus logger, which is more flexible and which does not cause such issues.

virtcontainers: Replace glog by logrus logger

---

ci/ci-setup.sh

The build script from CNI supposed building all the plugins we need has been renamed from "build" to "build.sh". We have to fix that in our CI script in order to let our build properly pass.

ci: Fix the build because of cni build name change

---

pkg/hyperstart/hyperstart.go
pkg/hyperstart/hyperstart_test.go
pkg/hyperstart/mock/hyperstart.go
pkg/hyperstart/multicast.go

This PR mainly adds a new function to our hyperstart package so that a consumer of this package can properly wait for the end of the CTL channel before to go further.
The implementation relies on a Go channel written by the multicast loop when it cannot read anymore on the CTL channel.

pkg: hyperstart: Wait for the end of the CTL channel

---

cc_proxy.go
hack/virtc/main.go
hypervisor.go
mock_hypervisor.go
mock_hypervisor_test.go
pkg/oci/utils.go
pkg/oci/utils_test.go
pod.go
qemu.go
qemu_test.go

There is no reason to configure the pod console path from the PodConfig because it is used only internally by the proxy and it is created by the hypervisor. That's why this PR takes care of removing the Console field from PodConfig, and provide an internal way for both hypervisor and proxy to be able to get this console path.

Make pod console path internal

---

api.go
cni.go
container.go
hook.go
hyperstart.go
pkg/hyperstart/hyperstart.go
pkg/hyperstart/multicast.go
pkg/oci/utils.go
pod.go
qemu.go

Because virtcontainers and its packages are all packages, we wanted to be able to specify from the caller (such as the runtime) a different logger than the default one.

Improve logging

---

proxy.go

Because we can pass an interface as a parameter, and receive another interface by using sendCmd() from proxy interface, this was a bit unclear about what we can expect from this function. This commit clarify the usage thanks to some comments.
Fixes #170

proxy: Clarify sendCmd() expected usage

---

api.go
api_test.go
cnm.go
container.go
errors.go
filesystem.go
filesystem_test.go
hack/virtc/main.go
hook_test.go
pod.go
pod_test.go
sshd.go
virtcontainers_test.go

This branch switches the logic around so that rather than passing blank `podID` and `containerID`'s around and then magically expanding them at quite a low level, the `podID` and `containerID` are set as soon as possible by `virtc`. This allows all functions to validate the parameters are not blank and return an error if they are [1].
The logic is complicated by the fact that in certain contexts -- for example when creating particular `podResource`'s -- `containerID` *may* be blank. To handle this, I've created a new function called `resourceNeedsContainerID()`.
Note that this is a proof-of-concept branch - the tests have not been updated so will fail.
------
[1] - This allows "fail-fast" behaviour which is less confusing when attempting to debug issues.

Check podID and containerID function arguments

---

pkg/oci/utils.go
pkg/oci/utils_test.go

As OCI spec stated, ocispec.Root.Path is either an absolute path or a
relative path to the bundle.

pkg: oci: fix container rootfs path

---

cc_proxy.go
hyperstart.go

Because we don't need to send/receive any IO to/from the pause container workload, there is no point in passing a token to the proxy.
That way, the proxy does not wait for a token to be provided, and therefore it does not expect a shim to connect.

cc_proxy: Don't provide a token for the pause container

---

api.go
cnm.go
network.go

Starting "docker run" commands with 3.0 runtime, we have detected some sporadic issues related to the thread ID. In case the thread ID is different from the process ID, if we set the current process
to a given network namespace, Docker CNM plugin cannot reach this network namespace because it will find the one tied to the process ID. There is only one case where this is working, we need the thread ID being the same than process ID.
The way to achieve this, we call runtime.LockOSThread() so that the main thread does not end up executed by another thread.
Then, the other issue is about using go routines when you call LockOSThread(). In that case, the go routine will be automatically assigned a different thread ID. And in our case, we are calling Do()
function which is using a go routine to …

cnm: Fix sporadic netns issue related to wrong thread ID

---

hack/virtc/README.md

Even if the single dash is supported, it is more generic to use double dashes when command line options are more than one character.

docs: Replace single dash with double dashes in README.md

---

api_test.go
container.go
hack/virtc/README.md
hack/virtc/main.go
hyperstart.go
pod.go
pod_test.go

This PR modifies slightly virtcontainers structures Pod and Process to have something working both with virtc CLI and OCI runtime.
This enables the support for cc-shim inside virtc so that we can use the entire chain (shim+proxy) with virtc CLI.

virtc: Add cc-shim support

---

api.go
container.go
errors.go
filesystem.go
hack/virtc/main.go
pod.go
sshd.go

Only expose the minimum set of standard errors
("virtc" uses ErrNeedPodID and ErrNeedContainerID).

errors: Make the standard errors private.

---

agent.go
api.go
container.go
hyperstart.go
noop_agent.go
noop_agent_test.go
pod.go
sshd.go

A lot of code related to the proxy and the shim was present inside hyperstart agent implementation. The problem is that this code is generic for any pod/container, and deserves to be shared across different agent implementations.
After all generic code has been moved from agent implementations to pod/container code, there is no point in having `start()` and `stop()` functions provided by the agent interface. Our agent implementations are empty for those functions, and we cannot think about a future usage for any future agent.
This PR fixes issue #202. It has been tested with the runtime and everything still works as before.

Move generic code out of hyperstart agent implementation

---

container.go
hack/virtc/README.md
hack/virtc/main.go
hyperstart.go
pkg/oci/utils.go
pkg/oci/utils_test.go
pod.go
qemu.go
qemu_test.go

There is a limitation regarding the ability to provide a different console than container's one in case we are trying to execute a new process on this existing container. Indeed, because the console is tied to the ContainerConfig structure, we have no way to specify a different console for another process.
This PR moves Interactive and Console fields from the structure ContainerConfig to Cmd, solving our current limitation.
This PR fixes issue #204.

Add the ability to specify a different console for a new process on an existing container

---

api.go
api_test.go

Previously ListPod() returned an error if the pod directory did not
exist. However, that is the normal situation on a system where no pods
have been created.
Renamed "TestListPodFailing" test to "TestListPodNoPodDirectory"
for clarity.

api: ListPod() should succeed if pod directory does not exist.

---

api_test.go

TestListPodFailingFetchPodConfig() and TestListPodFailingFetchPodState()
where testing StatusPod() not ListPod(), so rename the test names to
reflect this.

tests: Renamed tests to match the API being tested.

---

qemu.go
qemu_test.go

Because we rely on the MAC address to find the network interface, we don't need to enable the renaming by udev of the interface created.
More than that, because hyperstart agent waits for the interface to be ready before it can continue, we don't want the name of the interface found to change after we received the first uevent.
This PR fixes the issue explained here https://github.com/01org/cc-oci-runtime/issues/815 and fixed with https://github.com/01org/cc-oci-runtime/pull/832. Related to the topic: https://github.com/clearcontainers/hyperstart/pull/20.

qemu: Prevent udev from creating predictable network interface names

---

NEWS

Added Clear Containers 3.0 shim support
Added Clear Containers 3.0 proxy protocol support
Added self contained hyperstart package
Added full build scripts
Added hypervisor and pod debug options
Added command line and function arguments validity checks
Added logrus support, replacing glog
Added OCI runtime vendoring
Added structured and separated error definitions
Fixed networking support and unit testing
Fixed code layering by keeping generic code out of interface implementations
Fixed benchmarks
Shortlog:
432d20f qemu: Prevent udev from creating predictable network interface names
1f8daba container: Move Console from ContainerConfig to Cmd structure
9643a8a qemu: Don't append consoles for every container
3778d51 agent: Remove start() and stop() from the interface
f26b15e virtcontainers: …

0.7.0 release

---

api.go

StatusContainer() does not need to iterate through all containers after
it has found a matching container to return the status for.

api: Speed up container status query.

---

hyperstart.go

They won't necessarily work across partitions.

hyperstart: Do not use hard links

---

qemu.go

After we sent the QUIT command through QMP socket to the VM, we were just returning, assuming the VM was stopped. But in some cases, it can take a little bit more time for the VM to stop, causing issues with our benchmarks. Indeed, running the same VM with the same UUID was conflicting and the QMP sockets were not created because the previous VM with the same UUID was not stopped. This patch waits for a go channel indicating QMP socket has been disconnected, meaning the "real" end of the VM.
Fixes #199.

qemu: Fix benchmarks issues related to VM root cause

---

hyperstart.go
hyperstart_test.go
utils.go
utils_test.go

Initially we used a hardlink to create the pause binary to the needed location so that our pause container could use it from inside the VM. But hardlink had a limitation regarding cross partitions, and that's the reason we moved to symbolic link.
But symbolic links are not evaluated when the pause container rootfs was mounted, resulting in having the pause binary missing.
The only way to properly deal with those issues is to copy the binary to the expected location.

hyperstart: Copy pause binary instead of creating a symbolic link

---

qemu.go

qemu: Use virtio-net-pci for our network driver

---

hack/virtc/main.go
hypervisor.go
hypervisor_test.go
qemu.go
qemu_test.go

`Q35` is a more standard and upstream QEMU machine type that is a reasonably good alternative to `pc-lite`.
We now support it through virtcontainers, although the default machine type is still `pc-lite`.

Add QEMU Q35 machine type support

---

cnm.go
network.go

This commit gets rid of doNetNS() function as it is too complex and it introduces some sporadic issues related to the use of go routines and network namespaces at the same time. The cause of those issues
is about some processes/threads changing during the runtime, causing some confusion with the network namespaces used.
The only way is to really make sure everything is controlled by our library, meaning we make all of our network implementations rely on the same "safe" function safeDoNetNS(). This patch also improves this
function by calling into runtime.LockOSThread(). This implies that no matter who is the caller of this function, it will end up in the expected network namespace with the guarantee the thread won't change
during the execution.
This is solving all sporadic issues related …

network: Fix benchmarks sporadic issues with netns

---

CONTRIBUTING.md

Spaces between ']' and '(' cause the links not to be rendered.

CONTRIBUTING: Fix the md links

---

hack/virtc/README.md

The shim installation path has been changed to
/usr/libexec/clear-containers.

README: Change shim path in virtc README

---

network.go

Multicast snooping may be turned on the bridge depending on the
distro kernel config. Disable this explicitly to avoid kernel issues
related to multicast timer expiration.
Fixes #229

networking: Turn off multicast snooping on integration bridge

---

cni.go
cnm.go
hyperstart.go
network.go
qemu.go

We were not able to ping the network plugin bridge from inside the container, meaning something was not properly configured. Indeed, we were assigning the same MAC address to the veth inside the network namespace and to the network interface inside the VM.
The right thing to do is to retrieve the MAC address of the veth after it has been created by the network plugin, then assign it to the network interface inside the VM, and reset the veth MAC to a random one. That way, we make sure the traffic will be seen by the network bridge on the host (cni0 or docker0 for instance) as if it was coming from the veth pair MAC address. But the reality is that those packets actually come from inside the VM.

network: Fix wrong MAC address configuration

---

api.go
api_test.go

StatusPod() was constructing ContainerStatus objects, which is the job
of StatusContainer().
Previously, StatusContainer() was returning an array of
ContainerStatus's *without* the required container Annotations.
Updated TestStatusPodSuccessful() to test full PodStatus returned by
StatusPod().

api: Make StatusPod() call StatusContainer().

---

api.go
api_test.go
container.go

The container start time is approximate but is useful for runtime implementations. Particularly, it is needed to implement the "list" command for the OCI runtime.

Add process starttime for runtime list

---

api.go
api_test.go
pod.go

Added hypervisor configuration to PodStatus. The latter already held the
hypervisor type but adding the configuration will allow runtimes to
implement richer "list" and "state" commands which include hypervisor
configuration details.

api: Add HypervisorConfig to PodStatus.

---

api.go
api_test.go

StatusPod() was calling StatusContainer(), but both were calling
fetchPod() for the same pod.
Introduce statusContainer() that accepts a Pod to avoid the double call.

api: Remove call to fetchPod().

---

api_test.go

Stop TestStatusContainer() from failing due to a missing container start
time.

tests: Fix-up for Container start time.

---

container.go
pod.go

Previously, Process objects were created in separate parts of the code,
but were not consistent (only one set Process.StartTime).
Introduce newProcess() to centralise the creation of these objects.
Fixes #252.

container: Create function to create a Process.

---

pkg/oci/utils.go
pkg/oci/utils_test.go

The OCI configuration file path and the OCI bundle directory need to be
public to allow them to be used by runtime implementations.

oci: Make OCI config file and bundle directory paths public.

---

cc_shim.go
cc_shim_test.go

The console passed in the config needs to be set as the
controlling terminal for the shim. This is done so that the
shim receives signals regarding terminal changes as well as
terminal's interrupt(Ctrl-C) and quit key are sent to
the shim process.
Fixes #257

tty: Set the console as the controlling terminal for shim

---

pkg/oci/utils.go
pkg/oci/utils_test.go

When the pod is deleted we need to know the container's
annotations in order to be able to delete the pod.
fixes https://github.com/clearcontainers/runtime/issues/133

oci: copy container's annotations to pod

---

container.go
hyperstart.go
syscall.go
syscall_test.go

This adds support for the oci specification to mount
the rootfs as readonly.

rootfs: Support mounting the rootfs as readonly

---

agent.go
api.go
container.go
hyperstart.go
noop_agent.go
pkg/hyperstart/types.go
sshd.go

Allow all processes in a container to be killed.

api: Add 'all' parameter to KillContainer().

---

syscall_test.go

Use defer here, in case we succeed in creating a file in the
read-only bind mount, the unmount may not be called.

tests: Use defer with call to unmount

---

pkg/oci/utils.go
pkg/oci/utils_test.go

Now that read-only rootfs support has been added pass this to
the container config.
Should have been part of earlier PR, missed adding this.

oci: Pass the read-only config from the oci spec file

---

utils/virtcontainers-setup.sh

Because CNI recently moved all their plugins to a different repo, we have to update our scripts to make sure we can still build CNI plugins from sources. This is needed for our CI to continue to be functional.
The new repo is: github.com/containernetworking/plugins

utils: Fix the script installing CNI plugins

---

api.go
hack/virtc/main.go
pkg/hyperstart/hyperstart.go
pkg/oci/utils.go
virtcontainers_test.go

We don't really want a Logger object, but either a Logger or an Entry. Using the FieldLogger interface leaves a choice to users.
Took the opportunity to rename SetLog to SetLogger as well, looks slightly better to me.

Generalise *logrus.Logger to the logrus.FieldLogger interface

---

api.go
container.go
pod.go
shim.go
shim_test.go

In case a shim has been created because a pod or a container has been created, we don't want to end up with a call to DeleteContainer() or DeletePod() that could end up in one or several shims running with no container related.

shim: Stop the shim if container has only been created

---

api.go
api_test.go
hack/virtc/main.go
hypervisor.go
mock_hypervisor.go
pod.go
pod_test.go
qemu.go

Allow a pod to be paused (all processes suspended) and resumed (all
processes allowed to continue).
Fixes #267.

api: Implement PausePod() and ResumePod().

---

NEWS

Added pod pause and resume support
Added bind mounts support
Added CRI-O support
Added QEMU Q35 machine type support
Added readonly rootfs support
Added annotations passing to the OCI config file
Fixed hyperstart users and groups management
Fixed the installation and build scripts
Fixed networking MAC address configuration
Shortlog:
0b08b32 api: Implement PausePod() and ResumePod().
0e47e70 pod: Make state handling functions set in-memory state.
d2e6aaa mounts: Add function to perform unmounts
3719480 mounts: Store mounts after bind-mounts are handled
63cbcca state: Add functionality to store/fetch mounts to/from filesystem.
a249fde test: Add test for checking if a path is system mount
0ef264e mounts: Handle bind mounts
90ef63f container: Add comments for setContainerState().
6b8f0b5 …

1.0.0-rc.0 release

---

errors.go
filesystem.go

filesystem.go was creating a lot of identical error objects, so add a
new "errInvalidResource" standard error to avoid the duplication.

errors: Introduce standard error for invalid pod resource.

---

cnm.go
hyperstart.go
hyperstart_test.go
network.go

Until now, we were ignoring routes that we scanned in case the destination was nil, but we were missing the most important route, i.e the one redirecting everything else to the docker gateway (usually 172.17.0.1).

network: Handle routes with empty/nil destination as "default" destination

---

NEWS

Added standard error for invalid pod resources
Fixed docker gateway routing
Shortlog:
ba8cba8 hyperstart: Consider 0.0.0.0/0 route destination as default
147f06d cnm: Don't ignore routes with empty/nil destination
2e31e20 errors: Introduce standard error for invalid pod resource.

1.0.0-rc.1 release

---

container.go
hyperstart.go

SIGTERM could not be handled by some processes. Because this signal is sent to stop the container or the pod, that means we don't mind about the way those processes are terminated, and we make sure that SIGKILL will do the job.
To give you more context, I have realized that starting a container like that:
```
docker run -d busybox sleep 1000
```
and trying to stop it with:
```
docker stop 36d562a063e8111b670f9b8198c3692e84369b87a61f8b31f32226873b1a0977
```
was actually leading to an issue with our new agent. Okay so try to follow me here, there are several reasons for this change.
First you have to know that Docker issues a SIGTERM and after a timeout, if nothing happened (process still running), it issues a SIGKILL.
- If you make the test with `runc`, it will hang for 10 seconds (default …

container: Stop a container with SIGKILL instead of SIGTERM

---

pkg/oci/utils.go
pkg/oci/utils_test.go

Due to recent changes in CRI-O database, we have to rely on the sandbox ID and not the sandbox name anymore.

pkg: oci: Rely on sandbox ID instead of sandbox name

---

container.go
filesystem_test.go
pod.go

We were duplicating a bit of code, so we factorize it now.
Also, the single container creation case was wrong as it was
missing the container mount points.

container: Factorize container creation

---

api_test.go
container.go
pod.go
pod_test.go

This patch allows any container in StateReady state to be switched
to a StateStopped state, without doing further action than updating
the container state itself.

container: Add StateReady to StateStopped as valid transition

---

NEWS

Added support for transitioning from Ready to Stopped
Fixed pod container creation
Fixed CRI-O support for sandbox identifiers
Shortlog:
f6f4997 container: Add StateReady to StateStopped as valid transition
0693a26 vendor: Update vendoring to master branches
db39ee5 pkg: oci: Rely on sandbox ID instead of sandbox name
a93417c container: Rename createContainers
407bb96 container: Factorize container creation
d3429b8 container: Stop a container with SIGKILL instead of SIGTERM

1.0.0-rc.2 release

---

README.md
agent.go
capabilities.go
capabilities_test.go
container.go
hyperstart.go
hypervisor.go
mount.go
mount_test.go
noop_agent.go
pod.go
pod_test.go
qemu.go
qemu_test.go
sshd.go
utils.go
utils_test.go

In case of device mapper storage driver, the overlay file system is backed by a block device.
With this PR, we directly use the block device for container rootfs, instead of the overlay. As we do not go through 9pfs, this gives us much better I/O performance. We go through 9pfs only for the bind-mounts.

Use block device for container rootfs in case of devicemapper

---

hyperstart.go
pkg/hyperstart/types.go

The MTU parameter was working with hyperstart but it is only because
the cast worked. This patch makes sure that we are passing the MTU
as an integer as it is expected by hyperstart.

pkg: hyperstart: Fix MTU type from string to integer

---

NEWS

Added support for assigning the container rootfs underlying block device to the
VM (when using devicemapper)
Changed qemu to use virtio-net vhost by default
Changed qemu parameters to not be Clear Containers specific
Fixed MTU passing to hyperstart
Shortlog:
d10cac1 qemu: Remove Clear Containers specific kernel parameters
53d6cc4 hypervisor: Export the Param structure
76651e6 hypervisor: Implement helper for adding kernel parameters
5bb4196 qemu: Enable virtio-net vhost by default
b9292d2 pkg: hyperstart: Fix MTU type from string to integer
d2d23cf docs: Add documentation for the devicemapper storage scanario.
9a7b349 devicemapper: Use state vars to pass the blkdevice info to hyperstart
b7de0e1 state: Add fields to state for storing storage related info
359beef state: Update the entire …

1.0.0-rc.3 release

---

hypervisor.go
hypervisor_test.go
qemu.go
qemu_test.go

A runtime implementation can use these fields to setup the default
vCPU number and default memory size for new VMs.
VMConfig can overwrite these settings.
Signed-off-by: Dmitry Voytik <dmitry.voytik@huawei.com>

hypervisor: Add Default{VCPUs, MemSz} to HypervisorConfig

---

.pullapprove.yml

We are missing reviewers given the fact that some people are in
vacation and others are leaving.

CI: Add a new reviewer to pullapprove

---

cc_shim.go
cc_shim_test.go
container.go
pkg/mock/mock.go
pkg/oci/utils.go
pkg/oci/utils_test.go
pod.go
shim.go
shim/mock/shim.go

When a process is started as "detached" from one of the following
commands:
- cc-runtime run -d <containerID>
- cc-runtime exec -d <containerID>
we don't want to see the output posted on the current shell used,
instead we expect this to be silent.
Fixes #303

shim: Stop forwarding output in detach mode

---

cc_shim_test.go

Add new tests to bring unit test coverage for cc_shim.go to 100%.
Fixes #313.

tests: Increase unit test coverage for cc_shim.go.

---

qemu.go
qemu_test.go

We might need to switch to the pc machine type in the future. This
commits takes care of adding this new type as supported.
Fixes #320

qemu: Add pc machine type as supported

---

container.go
hyperstart.go
pod.go
shim.go
shim_test.go

In case we are stopping a pod or a container, for every container,
we send a SIGKILL signal and then we try to remove the container.
Unfortunately, if the process inside the container takes some time
to be killed, the removal of the container can sometimes fail.
This patch ensures that we are waiting for the end of the shim
process after we sent the SIGKILL signal. In case we hit a timeout,
the stop() will fail.
Fixes #318

stop: Wait for end of container process before to remove

---

agent.go
hyperstart.go
noop_agent.go
pod.go
sshd.go

The hyperstart agent implementation for init() interface was
performing setup such as adding devices with the hypervisor.
Since init is called during create, start and all other container
lifecycle stages, this setup was being performed repeatedly.
Introduce a new interface for agent called "createPod" that is
supposed to perform all the initial setup while creating a Pod.
Refactor hyperstart init() to exclude the device creation and move
that to createPod.

create: Split hyperstart init function to perform setup only at create

---

hypervisor.go
hypervisor_test.go
qemu.go

Add an exported function DeserializeParams(), and export
SerializeParams().
This patch is laying the ground work for [https://github.com/clearcontainers/runtime/pull/369](url)

hypervisor: export SerializeParams and DeserializeParams

---

api.go
api_test.go
container.go
noop_shim.go
noop_shim_test.go
pod.go

This PR fixes several small issues but all related as they globally fix/improve the way we handle a container (or pod) stop/kill and also the updates of the container state. This is needed for reworking properly our runtime implementation.
Fixes #327 
Fixes #328 
Fixes #329 
Fixes #330 
Fixes #331 
Fixes #332

Globally improves the handling of container/pod states

---

NEWS

Added new project approvers
Fixed gometalinter
Increased unit test coverage
Added "pc" machine type for Qemu hypervisor
Fixed "kill" and "stop" container
Shortlog:
1140aca hypervisor: export SerializeParams and DeserializeParams
89577b2 pod: Allow to stop a pod in ready state as a special case
8fdcb90 pod: Ignore container ready or stopped when stopping the pod
72a0be6 pod: Factorize pod stop() function
7f61c04 container: Don't issue an error if trying to stop a stopped container
10c592f container: Signal a ready container is valid but not stopping it
ae8fcbb api: Update the container status when retrieving its status
4e5128a create: Split hyperstart init function to perform setup only at create
57bec7d stop: Wait for end of container process before to remove
284dd91 qemu: Add pc machine …

1.0.0-rc.4 release

---

hyperstart.go

Currently we have hyper/tty socket in /tmp/{hyper,tty}-pod-id.sock. We should
move them to /run/virtcontainers/pods/id/{hyper,tty}.sock to be unified.
Fixes #270

hyperstart: move hyper and tty socket to per-pod runtime storage path

---

hypervisor.go
hypervisor_test.go
qemu.go
qemu_test.go

Setting maxmem to host memory size wouldn't change memory footprint. It
only defines the upper bounds for memory hotplug.
Currently we set maxmem to mem*1.5, which is not enough for running a
small VM (eg. 128M) considering nvdimm device consumes memory address
space.
This will also allow us to do memory hotplug (maybe in the future).

[RFC] qemu: set maxmem to host memory size

---

pkg/oci/utils.go
pkg/oci/utils_test.go

We should run VM(container) regarding OCI spec config.json memory limit.
-- 
This pull request resolves https://github.com/clearcontainers/runtime/issues/381
The original patch is at https://github.com/clearcontainers/runtime/pull/390

pkg: oci: support OCI spec memory limit

---

pkg/oci/utils.go
pkg/oci/utils_test.go

We should run VM(container) regarding OCI spec config.json cpu quota and
period.
The number of VM VCPUs is defined by quota/period (round up to 1).
-- 
Original issues is https://github.com/clearcontainers/runtime/issues/393

pkg: oci: support OCI spec cpu quota/period

---

hyperstart.go

this patch adds the user, group and additional groups in the process
structure used to create a container (newcontainer command)
partially fixes https://github.com/clearcontainers/runtime/issues/386

hyperstart: add suport for user, group and additional groups

---

Gopkg.lock
hypervisor.go
hypervisor_test.go
qemu.go
qemu_test.go
vendor/github.com/01org/ciao/.travis.yml
vendor/github.com/01org/ciao/DeveloperQuickStart.md
vendor/github.com/01org/ciao/README.md
vendor/github.com/01org/ciao/packages.json
vendor/github.com/01org/ciao/qemu/qemu.go
vendor/github.com/01org/ciao/qemu/qemu_test.go
vendor/github.com/01org/ciao/qemu/qmp.go
vendor/github.com/01org/ciao/qemu/qmp_test.go
vendor/github.com/01org/ciao/ssntp/server.go
vendor/github.com/01org/ciao/ssntp/ssntp_test.go

When Clear Containers runs on Azure, it actually runs inside an existing VM (nested VM) managed by Hyper-V hypervisor. And because KVM has some issues when running on a VMM, the only way to get Clear Containers working is to fallback from virtio 1.0 to a previous version, and to disable pmu.
We need to implement a way to detect VMM environment and enable/disable specific flags accordingly.
Fixes #342

qemu: Detect VMM environment to apply specific flags to our VM

---

pkg/hyperstart/hyperstart.go

Since we have two different agents now implementing
hyperstart protocol, make the error message in case of
the agent returning an error, a bit more generic to
avoid confusion.
Fixes #350

agent: Make the error message from agent generic.

---

pkg/oci/utils.go
pkg/oci/utils_test.go

StatusToOCIState() does not need to return an error as there are no
error scenarios to deal with.
Fixes #354.

oci: Remove error return from StatusToOCIState()

---

hyperstart.go
pkg/oci/utils.go
pkg/oci/utils_test.go
pkg/oci/utils_test_config.go
pod.go

Hostname was incorrectly being set to the pod-id.
It should instead be set to the hostname passed in the spec
file. The hostname passed is usually the shortened pod-id.
This should fix the command prompt seen when exec'ed into
a container to be the same as runc.
Fixes #361.

oci: Set hostname to the one passed in spec file

---

qemu.go

%v should work for booleans.
Fixes #363

qemu: Typo fix

---

container.go
hyperstart.go
pod.go
qemu.go

From Info to Debug. They clutter any runtime log using virtcontainers
at Info level.
Fixes #365

log: Downgrade pod, container and hyperstart config dumps

---

README.md

Since hotplug support has been added, it is now possible
to use block devices for containers started after VM has started.
Update docs to reflect this change.
Fixes #368

docs: Update documentation for hotplug support.

---

api_test.go
container.go
hyperstart.go
network.go
pkg/oci/utils.go
pkg/oci/utils_test.go
pod.go

cc-runtime was failing to start a container with a non exiting container ( expected ) but delete cleanup was not properly handled.
This PR add fixes for:
https://github.com/clearcontainers/runtime/issues/507
1. Because the start the container failed, we should stop the shim (indicate the process is not running)
2. The runtime should use oci config.json only at create after that it uses its state file to perform following operations. We were saving the config.json path in virtcontainers annotations, lets save the json content. 
This allow cc-runtime to get information related with the config even if does not exist anymore.

Fix pod deletion after a failed start under docker.

---

hypervisor.go
qemu.go

Add support for pre-allocating all the RAM for the VM. This will reserve the RAM at VM startup.
Also add support for realtime and mlock.
Enabling prealloc, realtime and mlock gives the lowest latecy.
Disabling prealloc, enabling realtime and disabling mlock gives highest density as the memory will be swapped.
This PR depends on vendoring the updated qemu package. https://github.com/01org/ciao/pull/1428 and
https://github.com/01org/ciao/pull/1430

Memory Preallocation: Add support for pre-allocation

---

.pullapprove.yml
OWNERS

Damien is no longer working on this project (afaik) - drop him
from the pullapprove and OWNERS files.
Fixes: #377
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

approvers: dlespiau no longer working on this

---

hyperstart.go

Or else docker --read-only is not supported.
Fixes: clearcontainers/runtime #614

hyperstart: Pass the read only flag to the rootfs bind mount

---

hypervisor.go
qemu.go

This is used to disable the customizations performed when
we are running on top of another VM. This can be used when
running on top of KVM to obtain the best performance.
This check should not be disabled when running on hypervisors
other than KVM. Doing so will result in failure to launch.

Nesting: Disable nesting checks

---

api.go

Make SetLogger() add a "source=" field to the provided logger to allow
individual log entries to be attributable to this package.
Fixes #386.

logging: Add source field

---

hypervisor.go
qemu.go

Add support to launch virtual machines where the RAM is
allocated using huge pages. This is useful for running
with a user mode networking stack, and for custom setups
which require high performance and low latency.
Note: Needs revendoring of ciao/qemu changes https://github.com/ciao-project/ciao/pull/1449

Huge Page Support: Add support for huge pages

---

NEWS

Added James Hunt as maintainer
Added huge pages support
Added option for disabling nesting optimizations
Fixed the rootfs readonly support
Shortlog:
ad8449a vendor: Weekly update
27902cf Huge Page Support: Add support for huge pages
e6b2988 logging: Add source field
0b6d279 OWNERS: Add James O. D. Hunt
ab657b5 hyperstart: Pass the read only flag to the rootfs bind mount
bcb61c9 approvers: dlespiau no longer working on this
742c575 Nesting: Disable nesting checks

1.0.2 release

---

pod.go
qemu.go

VMs can take a little while to get going depending on the
circumstances - such as a very busy or a large (cores and RAM)
VM - 1s is not long enough to wait in such cases. Bump the
startup timeout (it is better to wait 'too long' to realise
something broke, rather than firing false failures)
For now we make the concious decision to leave the VM shutdown
timeout at 1s.
Fixes: #390
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

pod: startup: Wait longer for the VM to start

---

api.go
qemu.go

This PR allows to fix the CRI-O testing issues that have been observed recently. The root cause of this is the lack of locking regarding the Pod resource when using `StatusPod()` or `StatusContainer()` functions.

api: Fix pod race conditions

---

network.go
network_test.go

Ignore the non namespaced tunnel base devices like gre0, tunl0,
sit0, ipip0 etc. Also ignore any devices that do not have ip
address configured.
Fixes https://github.com/containers/virtcontainers/issues/391

Networking: Ignore invalid and unconfigured interfaces

---

container.go
device.go
device_test.go
hyperstart.go
pkg/oci/utils_test.go

The agent does not fully support RO rootfs
Unmarshalling device interfaces is not possible with our device structures.
We need to implement our custom marshalling and unmarshalling routines
in order to properly create the right devices from a stored container config.

Implement custom devices marshalling routines and revert RO rootfs support

---

NEWS

Added initial device assignment framework
Added VFIO devices assignment initial support
Fixed pod locking
Fixed unconfigured interfaces handling
Shortlog
3802796 tests: Fix oci tests for device handling.
64e868c container: Implement custom devices marshalling routines
7b8ee42 hyperstart: Temporarily revert rootfs ro support
f2ba9f1 Networking: Ignore invalid and unconfigured interfaces
24c8394 api: Add missing pod locks
51a6d33 qemu: Increase the timeout when stopping the VM
77b5ef7 devices: Add attachDevices and detachDevices for pods and container.
f23109c vfio: Handle attaching vfio devices.
7e607e2 qemu: Add vfio-passthrough to qemu.
3a40fdd tests: Add tests for creating devices.
98af546 vendor: Vendor github.com/go-ini/ini
efc00b9 devices: Parse Linux devices from oci spec.
a9f589f …

1.0.3 release

---

cc_shim.go

Add a new option to `CCShimConfig` to allow `cc-shim` debug output
to be enabled.
Fixes #401.

shim: Add ability to enable debug output

---

Gopkg.lock
vendor/github.com/01org/ciao/CONTRIBUTING.md
vendor/github.com/01org/ciao/packages.json
vendor/github.com/01org/ciao/qemu/qemu.go
vendor/github.com/01org/ciao/ssntp/README.md
vendor/github.com/01org/ciao/ssntp/ssntp.go
vendor/github.com/01org/ciao/ssntp/ssntp_test.go

To allow the use of custom bios in virtcontainer we need to
update ciao to the latest commit
short log:
c73deac bios: add support for custom bios
19f008d ciao-deploy: Keep going if any unjoin step fails
9998583 configuration: Remove "compute_fqdn" from configuration
0b88648 ciao-controller: Use certificate common name as canonical name
b760589 storage_bat: Test that detaching from active instance fails
a524e08 singlevm: Do not access $GOPATH directly
1c4a091 singlevm: Move singlevm to use ciao-deploy setup
3d858df ciao-deploy: When an SSH command fails report stdout/stderr
9716e2d testutil: Remove unused code
47defc0 misc: remove remnants of ssntp.DetachVolume/ssntp.DetachVolumeFailure
6e2f8bb Add node failure stats to ciao nodes
5d50323 ciao-controller: update unit test to detach from …

vendor: update ciao

---

hypervisor.go
qemu.go

In order to support custom BIOS, nofw option
must be removed and the Bios must be set with
the path to it
partially fixes https://github.com/clearcontainers/runtime/pull/687

qemu: support custom bios

---

container.go
device.go
device_test.go
filesystem.go
pkg/oci/utils.go
pkg/oci/utils_test.go
pod_test.go

Refactor the way devices are handled so that we store an invariable config set in the configuration.
This PR moves the Device interfaces from ContainerConfig to Container and create the device implementations at create stage.
Devices are store separately in "devices.json". This simplifies the custom marshalling and unmarshalling to an extent.

Refactor device handling

---

.ci/ci-setup.sh

Specify to sudo the PATH to use to execute the
virtcontainers-setup.sh script. If we do not specify the PATH,
the system will not find `go`
Fixes: #407

ci: Fix call to virtcontainers-setup.sh

---

cc_shim.go
cc_shim_test.go
container.go
pod.go
shim.go
shim/mock/shim.go

Pass the container ID to `cc-shim`, using its existing `-c` option,
to allow it to produce more useful log messages.
Fixes #414.

shim: Pass container ID using CLI option

---

hyperstart.go
pod.go

Don't log huge objects unless a problem occurs to quieten down the
amount of log output generated by default.
Fixes #424.

logging: Log less by default

---

.ci/ci-jobs.sh
hack/virtc/main.go
pkg/oci/utils_test.go
pkg/vcMock/pod.go

Azure CI is failing due to go-vet errors of "composite literal uses
unkeyed fields". Use keyed fields in structs to fix the issue.

ci: Fix go-vet errors

---

Gopkg.lock
Gopkg.toml

Switch the vendoring model from a mix of Branch and Semver tags
to one that uses locked Revision.
This will mean that each dependency has to be updated explicitly
by the user in the Gopkg.toml file. This is different from the
current model where a prune and dep ensure by a user will
pick up the current tip of the each branch.
This will mean each dependency will have to be explicitly
vendored and updated using revision number.
However longer term it means that we will no longer have vendoring
mismatches between common dependencies across virtcontainers
and the clearcontainer runtime, enabling easier dependency management.

Vendoring: Use revision locked vendoring model

---

device.go
device_test.go

Ability to obtain device names from major-minor number of device
was added in kernel 2.6.27 version:
torvalds/linux@e105b8b
But for certain devices like /dev/cuse, /dev/fuse, this sysfs
interface may not exist. This may also depend on the kernel
version used.
We are primarily using this sysfs interface to obtain device name in
case the renamed device name was passed to the runtime.
To accomodate these devices, which are passed by docker by default
for priveleged/non-priveleged containers, we ignore the missing file
error for /sys/dev files and assume device name passed in the oci spec
file for such devices is not the renamed device name.

Ignore sysfs missing uevent file error, ignore "/dev/vfio/vfio"

---

device_test.go

If the uevent file in /sys/dev/ is not found, we added a change to
ignore this error. Add test to check this behaviour.
Also, test should have been changed from a helper function.
Fix that as well.

tests: Add tests to check the changes made to ignore uevent error

---

pod.go

When setting a pod state, we don't want to overwrite its existing values
by storing an empty pod state with all block and fs states unitialized.

pod: Do not overwrite pod state

---

api.go
container.go
container_test.go
pod.go

When mixing cold and hot plugged devicemapper drives, orchestration
engines can get confused and removing pods can fail as the assumption
that a stopped pod pause container rootfs can be unmounted fails with
virtual machines.
Fixes #435

pod: Hotplug all pod container rootfs with devicemapper

---

NEWS

Added shim debug output
Added support for custom qemu accelerators
Added structured logging
Added drive hotplug support for all containers
Fixed pod block index accounting
Fixed vendoring model
Shortlog
c490764 container: Rename addDrive to hotplugDrive
e848de5 pod: Hotplug all pod container rootfs with devicemapper
d7e3297 pod: Do not overwrite pod state
8b229ca tests: Add tests to check the changes made to ignore uevent error
6eb81de log: Log devices that are not passed to the container.
8a998f8 devices: Add corner case check for /dev/vfio/vfio
f7d0732 devices: Ignore error from missing sysfs path under /sys/dev
3ae5af6 .ci: Pass go env variables to sudo.
8098674 ci: Fix go-vet errors
ccd0c75 logging: Use structured logging
7867430 logging: Log less by default
c03bca6 Vendoring: Use …

1.0.4 release

---

.ci/jenkins_job_build.sh

This commit adds a script that will be executed in jenkins to help
simplify the jenkins setup maintenance.

CI: Add script for jenkins job

---

agent.go
api.go
api_test.go
cc_proxy.go
container.go
hyperstart.go
implementation.go
interfaces.go
noop_agent.go
pkg/hyperstart/hyperstart.go
pkg/hyperstart/types.go
pkg/vcMock/mock.go
pkg/vcMock/mock_test.go
pkg/vcMock/types.go
sshd.go

ps command is used to list the processes running inside
the container, this command is called by ```docker top```
partially fixes clearcontainers/runtime#95

 agent: implement ps command

---

qemu.go

The message that shows if running inside a VM was being displayed as a
raw golang variable ("%!q(bool=true)") rather than a "true"/"false"
string.
Fixes #449.

qemu: Fix incorrectly formatted log message

---

cc_proxy.go
proxy.go

If a proxy cannot be connected to, retry for a period of time until a
timeout (5 seconds) is reached. Output rate-limited log messages to show
connect progress when an immediate connection is not possible.
Fixes: #446.

proxy: Retry if unable to connect.

---

container.go
device.go
device_test.go
hyperstart.go
pkg/hyperstart/types.go
pod.go

Add support for passing block devices to a container with --device. This PR passes block devices to the VM using virtio-block.

Block device support for --device

---

.ci/setup.sh

chronic command is not available in Fedora and to support Fedora
in our CI we can get rid of this tool in this part of the setup.

ci: Remove chronic from setup.sh

---

README.md

Removes Semaphore CI badge and adds ubuntu 16.04 and fedora 26
badges.

readme: update CI build badges

---

api.go
api_test.go
pod.go

This PR introduces shared locks so that it can improve the locking strategy. Basically, it takes a shared lock when a function only needs to read from the system, and it takes an exclusive lock when a function needs to modify what's written on the system.
Fixes #421

lock: Improve locking strategy

---

hack/virtc/main.go

With recent changes brought to the Clear Containers runtime, virtc
was not really in sync with what we were currently testing. This
patch replaces the systemd target file to be run by the guest kernel
and it also enhances the handling of the hypervisor machine type.
By default, we want to rely on "pc" machine type (with the proper
uncompressed kernel associated), and through the CLI, we can choose
"pc-lite" which will be automatically associated to the compressed
kernel.

virtc: Fix virtc to make it properly usable

---

Gopkg.lock
Gopkg.toml
hyperstart.go
network.go
qemu.go
utils.go
vendor/github.com/vishvananda/netlink/handle_linux.go
vendor/github.com/vishvananda/netlink/handle_test.go
vendor/github.com/vishvananda/netlink/link.go
vendor/github.com/vishvananda/netlink/link_linux.go
vendor/github.com/vishvananda/netlink/link_test.go
vendor/github.com/vishvananda/netlink/nl/nl_linux.go
vendor/github.com/vishvananda/netlink/nl/nl_linux_test.go

Networking: Add support for multi-queue mactap
Provide multiple methods to connect the Virtual machine
to the container network. The current implementation allows
this to be chosen at a node level. In the future we can
enhance this to be dynamic, where the container interface
type is used to determine the optimal interconnection method.
Add support for multi-queue macvtap as an alternate means to
connect the container network interface to the virtual machine.
Depends on: https://github.com/ciao-project/ciao/pull/1510
Depends on: https://github.com/containers/virtcontainers/issues/410

Use macvlan to connect the VM to the container network

---

.ci/update-vendoring.sh
CONTRIBUTING.md

When a pull request is submitted to virtcontainers, the CI will run,
testing the whole compatibility with Clear Containers runtime.
Unfortunately, when this PR involves some changes in virtcontainers
API or structures, the CI fails because the runtime cannot be built.
This commit introduces the possibility to specify a new field in the
commit message of the last commit of the pull request submitted to
virtcontainers.
The documentation has been updated to explain how to use this tag.

.ci: Handle cases where backward compatibility is broken

---

.ci/setup.sh

As chronic is actually available on Fedora with the moreutils
package, lets restore the use of chronic in this script.

ci: restore the use of chronic

---

NEWS

Added full CI (unit, functional and integration tests)
Added docker ps command support
Added multi-queue macvtap to the list of networking models
Added --device support for block devices (emulated)
Added pod shared locks for more efficient locking
Removed the ciao uuid package dependency
Shortlog:
8be82a3 ci: restore the use of chronic
f4a2ad1 virtc: Fix virtc to make it properly usable
b366203 .ci: Handle cases where backward compatibility is broken
e2f5902 lock: Use shared locking for read only cases
5e18bdf lock: Introduce shared lock possibility
809eb65 readme: update CI build badges
ad66bff ci: Remove chronic from setup.sh
eea3d36 tests: Add test to check attaching block device
dbad689 devices: Try to restore the pod block index in case of failure.
1e69ba9 devices: Add block devices …

1.0.5 release

---

container.go

Change fetchContainer() to only dump the config to the log on error.
Fixes #466.

container: Quieten logging

---

.ci/jenkins_job_build.sh

Coveralls needs its report to be performed against master branch to
report properly the code coverage to Github.

.ci: Fix coveralls reports

---

asset.go
asset_test.go
hypervisor.go
pkg/annotations/annotations.go
pkg/oci/utils.go
pod.go
pod_test.go
qemu.go

Based on the pod config annotations, we change the underlying
hypervisor configuration. Pod config annotations can carry a
kernel, image, hypervisor and firmware paths.
Those annotations, if valid, will supersede the hypervisor
configuration paths. If not valid, virtcontainers will error
out.
Optionally, asset SHA-512 hashes can be passed through pod
annotations as well. In that case virtcontainers will verify
that the asset binary matches the hash annotation and error
out when it does not.
More details on the architecture in #439 
Fixes #439
TODO:

Multi OS support

---

filesystem.go
filesystem_test.go

The way we have been handling the fetch was too rigid and was forcing
us in doing several changes when adding new types of files.
With this commit, we rely on the magic of Go unmarshalling. The JSON
package handle all the complexity for us, allowing much more flexible
code.

storage: Simplify fetches from storage

---

api.go
container.go
pod.go

The way CreatePod() was implemented, it was making an extra call
to hotplug all the drives. But when StartPod() is called, it leads
eventually to Container.start() to be invoked, resulting into a
hotplug of the drives related to this container.
A mechanism based on a flag was in place to detect if the drive had
been previously hotplugged, but there is no need for such thing
anymore. Indeed, we know that we are hotplugging only from the
container implementation.

api: Simplify drive hotplugging

---

filesystem.go
filesystem_test.go

In a previous patch, I have been simplifying the way we were fetching
stored information from the filesystem, but I simplified too much,
because I forgot the specific case of devicesFileType.
This commit fixes this lack of support by calling into the specific
function fetchDeviceFile() in case of devicesFileType as a resource.

filesystem: Fix fetchFile behaviour for devicesFileType

---

container.go

There is a limit size of 31 character for device ids in qemu 2.9.
This patch reduce the size of the id used to hot plug container's rootfs
as block device.
fixes #479

container: fix device mapper hot plug in qemu 2.9

---

api_test.go
bridge.go
bridge_test.go
filesystem.go
hypervisor.go
hypervisor_test.go
mock_hypervisor.go
mock_hypervisor_test.go
pod.go
qemu.go
qemu_test.go

Qemu Q35 machine type does not support to hot plug devices
directly on pcie.0, hence we have to find a way to allow users
hot plug N devices.
The only way to hot plug devices in Qemu Q35 is through PCI brdiges.
Each PCI bridge is able to support until 32 devices, therefore we have a
limitation in the amount of devices we can hot plug.
This patch adds support for hot plugging devices on PCI bridges in
pc and q35 machine types.

 hypervisor: add hot plugging support for Qemu Q35

---

hypervisor.go
mock_hypervisor.go
mock_hypervisor_test.go
pod.go
qemu.go

pod: Improve pod create performances
In order to optimize pod creation, this patch does not wait for the
VM after it has been started. Instead, it will wait for it during the
"start" stage. This will allow our VM to be started while the caller
could potentially do other things between create and start. Globally,
this improves the boot time of our containers.

pod: Improve pod create performances

---

api.go
api_test.go

Introduce some private functions to allow RunPod() to behave exactly as
if CreatePod() + StartPod() had been called instead. Removing the
duplicated code ensures the behaviour between the two methods for
creating and starting a pod is consistent.
Note that this change modifies the RunPod() behaviour very slightly -
the locking is now handled later, as was previously being done by
CreatePod() + StartPod().
Fixes #485.

api: Refactor RunPod()

---

hyperstart.go
pod.go
qemu.go
qemu_test.go

This PR first improves the way the tear down of the pod is performed from the agent. Until now, nothing was done and the VM was stopped without tearing down properly the things previously set up inside the VM.
Then, it modifies the QEMU implementation for the `stopPod()` method, by not waiting for the VM to exit. Instead, it send a SHUTDOWN through QMP but it does not wait for the VM since there is really nothing it can do.

pod: Improve pod stop/delete sequence

---

container.go
device.go
filesystem.go
hack/virtc/main.go
hyperstart.go
pod.go
qemu.go

Some "if" checks are redundant, we can remove them and return error
directly instead.
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

Remove redundant "if" checks

---

cni.go

After scanning the network namespace, we need to update the scanned
endpoints with the DNS information, and use the scanned endpoints
thereafter discarding the endpoints structures we had created prior
to calling into the CNI plugin.
There was a bug in the update, which was causing the entire endpoint
structure being assigned back to the scanned endpoints causing us to
lose information from the scan including if a virtual or physical
endpoint was found in the scan.

cni: Fix bug while updating endpoints after scanning net namespace

---

api.go
api_test.go
cc_proxy.go
cc_proxy_test.go
container.go
hack/virtc/main.go
noop_proxy.go
pod.go
proxy.go

proxy: Launch one proxy instance per pod
Create a proxy instance for each pod (virtual machine).
Since the proxy is now launched by virtcontainers, it is necessary to specify the path to the proxy binary
in the pod configuration.
Fixes #478.

One proxy per vm

---

network.go

getLinkByName() was making a log call but specifying the wrong logging
function meaning the parameters were not being logged correctly.
Fixes #501.

Fix network warning message

---

pkg/hyperstart/hyperstart.go
pkg/hyperstart/hyperstart_test.go

In case the agent returns an error, we simply return a very
generic message "Error received from agent". This is not very
helpful, the error should include the actual control message
received as well to help debug errors.

agent: Return the actual error returned by the agent

---

container.go
container_test.go
hyperstart.go
pkg/hyperstart/types.go

Introduce a new variable "BindMountDev" to indicate the case where
/dev is passed as a volume on the docker command line.
This case needs to be handled by the agent.

agent: Check for -v /dev:/dev case

---

agent.go
cc_proxy.go
cc_proxy_test.go
hack/virtc/main.go
hyperstart.go
kata_proxy.go
kata_proxy_test.go
no_proxy.go
no_proxy_test.go
noop_agent.go
noop_agent_test.go
noop_proxy.go
pkg/oci/utils.go
pod.go
proxy.go
proxy_test.go
sshd.go

This PR implements proxies for Kata Containers cases with and without proxy.
In order to achieve this, it slightly modifies the agent interface by adding two new functions.
Fixes #515 #516 #524

proxy: Introduce no_proxy and kata_proxy implementations

---

Gopkg.lock
Gopkg.toml
vendor/github.com/intel/govmm/qemu/qemu.go
vendor/github.com/intel/govmm/qemu/qemu_test.go

We want VSOCK for the kata_agent implementation
Short log:
5316779 qemu: Add VSOCK support

vendor: Revendor govmm for VSOCK support

---

cni.go
network.go
network_test.go
pkg/oci/utils.go

Some of the function naming and process around CNI's add() were overly complicated and/or obfuscated.
Initially, the CNI "add" function would create a virtual device which
would then be used to store the results obtained from calling the CNI
plugin.  This patch removes that, and instead keeps the netinfo results
for application to the endpoint device when we identify it post-scan.
Renamed addVirtInterfaces and deleteVirtInterfaces functions.
add is now invokePlugins, since this is what is carried out, and
the "virt" is removed from delete since there is nothing specific
to virtual in this case (it just invokes delete command to the plugin).
The function prototype for invokePlugins was also modified to return
the resulting netinfo from the CNI call, allowing the DNS information
to be used …

Network refactoring/cleanup

---

.ci/jenkins_job_build.sh
.ci/update-vendoring.sh

ci: Handle complex revendoring cases
This commit relies fully on dep tool so as to vendor the latest code
coming from a pull request on virtcontainers repository.
The information about the github repo URL and the commit revision are
both passed from Jenkins (as environment variables), and the script
relies on those values in order to override Gopkg.toml for both proxy
and runtime repositories.
The last step is to run dep tool, leaving the revendoring complexity
(including nested vendoring sometimes) being handled by dep.
Fixes #513

ci: Handle complex revendoring cases

---

qemu.go
qemu_test.go

setting the last pci bus to 0 reduces the kernel
boot time for around 40ms

qemu: improve kernel boot time

---

container.go
container_test.go

There was a bug in the way we were checking if /dev was
bindmounted from the host.

mounts: Fix bug while checking if /dev was bind-mounted

---

pkg/oci/utils.go
pkg/oci/utils_test.go

the number of vCPUs must be calculated using CPU period and quota
doesn't matter if a memory limit was specified or not
fixes #540

pkg/oci: honour CPU period and quota

---

Gopkg.lock
Gopkg.toml
kata_agent.go
vendor/github.com/kata-containers/agent/agent.go
vendor/github.com/kata-containers/agent/codecov.yml
vendor/github.com/kata-containers/agent/grpc.go
vendor/github.com/kata-containers/agent/protocols/grpc/agent.pb.go
vendor/github.com/kata-containers/agent/protocols/grpc/agent.proto
vendor/github.com/kata-containers/agent/protocols/grpc/health.pb.go
vendor/github.com/kata-containers/agent/protocols/grpc/oci.pb.go
vendor/github.com/kata-containers/agent/reaper.go
vendor/golang.org/x/crypto/ssh/certs.go

So that all runtimes based on virtcontainers will pull the same
kata agent commit and thus the same gRPC API.

vendor: Force kata containers agent vendoring

---

kata_agent.go
shim.go

The Kata containers shim needs to be SIGUSR1 signalled.
See https://github.com/kata-containers/shim/pull/19

kata_agent: Signal our shim

---

.ci/update-vendoring.sh

Dep tool was missing, and this was causing the revendoring to fail,
leading the CI to test cc-runtime based on virtcontainers master
branch.
Fixes #545

ci: Install missing dep tool

---

.gitignore

After new shim mocks have been added to the repository, we forgot to
add their binary names to the gitignore list.

gitignore: Add new shim binary to gitignore list

---

kata_shim.go

Fixed the CLI flag that is passed to `kata-shim` to run it in debug
mode.
Fixes #550.

shim: Correct kata debug flag

---

pod.go
qemu.go

The full name of the QMP monitor and control sockets was well
beyond the 107 character limit, resulting in the full name to
be truncated during creation.  As a result, only a single socket
was created.
Instead of creating a socket at
<parentDirPath>/<q.state.UUID>-<socketName>, create it at
<parentDirPath>/<socketName>-<q.state.UUID>, keeping as much of the
unique socket name as feasible.
Also, to reduce truncation the ".sock" from the socket names were removed.
Fixes #552
Signed-off-by: Eric Ernst <eric.ernst@intel.com>

qemu: adjust QMP naming to avoid non-unique truncation

---

agent.go
container.go
hyperstart_agent.go
kata_agent.go
kata_proxy.go
kata_proxy_test.go
mount.go
pkg/mock/mock.go
qemu.go

Now that we can test all kata containers components with virtcontainers, here is my first round of fixes:
- Build and store a default gRPC socket.
- Move the gRPC client handling from kata_agent to kata_proxy.
- Misc fixes from Sebastien.

Kata agent and proxy fixes

---

pkg/hyperstart/hyperstart.go
pkg/oci/utils.go

Change the `SetLogger()` API calls in the `oci` and `hyperstart`
packages so that they set the `source` logger field. This allows
callers making use of these packages to see the true source of the log
messages (previously, it would appear that log calls made by these two
packages would be coming *from* the caller itself).
Fixes #571.

logging: Set source field for oci and hyperstart packages

---

Gopkg.lock
Gopkg.toml
vendor/github.com/kata-containers/agent/Gopkg.lock
vendor/github.com/kata-containers/agent/Gopkg.toml
vendor/github.com/kata-containers/agent/agent.go
vendor/github.com/kata-containers/agent/agent_test.go
vendor/github.com/kata-containers/agent/api.go
vendor/github.com/kata-containers/agent/channel_test.go
vendor/github.com/kata-containers/agent/config_test.go
vendor/github.com/kata-containers/agent/grpc.go
vendor/github.com/kata-containers/agent/mount.go
vendor/github.com/kata-containers/agent/protocols/grpc/utils.go

We need this revendoring to fix the spec converter. We are relying
on the OCI to GRPC spec converter provided by kata agent, and this
has been recently fixed. We need this fix to go in for virtcontainers.
Shortlog:
045c2cf grpc: Split execProcess in more readable functions
71dd0b8 protocols: grpc: Fix the spec converter regarding nil pointers
532325c grpc: Move sequencing from StartContainer to CreateContainer
3dd881f grpc: Reference appropriate process when starting a container
b2f30e1 grpc: Lock the container creation
92a2a6a grpc: Remove unused code parts
d3a27ca agent: Add missing nsenter import
4f73ac9 mount: Create destination directory for 9pfs as well
1327404 mount: Do not shadow absSource
0759700 grpc: Return nil from SignalProcess() if container already stopped
9d6298b vendor: …

vendor: Update kata agent vendoring

---

container.go
kata_shim.go
pod.go
shim.go

Some shim implementation (like Kata) might need to know if a
terminal has been setup or not. This patch relies on Interactive
field from the Cmd structure that was never really used but
already holding this information.

shim: Carry the info about terminal

---

agent.go
agent_test.go
api.go
container.go
filesystem_test.go
hyperstart_agent.go
kata_agent.go
kata_proxy.go
noop_agent.go
noop_agent_test.go
pod.go
pod_test.go

Right now the virtcontainers core code explictly starts shims as soon as possible, regardless of the shim implementation being able to handle non existing containers or not.
This PR reorders that sequence and guarantees that shims will not be started before their corresponding container process is not started.
Now we have:
- container.go `createContainer` basically only allocate a new container structure and asks the agent to create it on the guest.
- It is up to each agent implementation to decide if there's a need to associate a shim to a container's process or not. i.e. the agent is now responsible for launching the shims.
- pod.go `startShims` is now `createContainers()` and calls into `createContainer()` for each configured container.

Start shims after creating containers

---

kata_agent.go

Only the unmounting of the container rootfs was performed, leaving
behind all the other mounts related to the container.
Fixes #562

kata_agent: Unmount properly the container

---

agent.go
agent_test.go
api_test.go
cc_proxy.go
cc_proxy_test.go
container.go
filesystem.go
hack/virtc/main.go
hyperstart_agent.go
hyperstart_agent_test.go
interfaces.go
kata_agent.go
kata_agent_test.go
kata_proxy.go
no_proxy.go
no_proxy_test.go
noop_agent.go
noop_agent_test.go
noop_proxy.go
pkg/mock/cc_proxy_mock.go
pkg/vcMock/container.go
pkg/vcMock/pod.go
pod.go
pod_test.go
proxy.go
proxy_test.go
shim.go

This PR mainly reworks the proxy interface of virtcontainers, pushes shim and proxy down the stack, that is hidden behind the agent.
Fixes #518

virtcontainers: Global re-organisation of the proxy/shim code

---

Makefile

Check before attempting to delete a file that it exists
(and is not "/").
Fixes #555.

build: Only clean files if they exist

---

agent.go
api.go
container.go
device.go
hyperstart_agent.go
kata_agent.go
mount.go
noop_agent.go
noop_agent_test.go
shim.go

The goal of this pull request is to enable the support for block devices for Kata Containers. It appeared that our sequence in container.go was tied to the hyperstart agent expecting things to be hotplugged only at the start stage. In case of Kata Containers, we need this to happen at the creation stage. This won't hurt the case for the hyperstart agent, and this will make it work for Kata too.
Now this pull request also solves other issues about implicit update of the mount list that has been discovered while trying to solve the initial problem. That's why it also refactor a bit the way bind mounts from each agent implementation actually updates the list of mounts held by the container structure.

container: Change block device hotplug ordering to get it effective on Kata Containers agent

---

pkg/annotations/dockershim/annotations.go
pkg/oci/utils.go

Dockershim use container labels to identify whether a docker container is a sandbox or a regular container.
I have sent a PR https://github.com/moby/moby/pull/36181 in moby project to pass the label to the annotations of OCI runtime spec.
This commit add support for dockershim pod annotations.
/cc @sameo 
Signed-off-by: Yanqiang Miao <miao.yanqiang@zte.com.cn>

Add support for dockershim pod annotations

---

qemu.go

The maximum number of CPUs per VM recommended by KVM is 240.
To support this amount of CPUs, the CPU topology must change
to 1 CPU 1 Socket, otherwise the VM will fail and print next
error message:
qemu: max_cpus is too large. APIC ID of last CPU is N
fixes #597

qemu: change CPU topology to support until 240 CPUs

---

cni.go
cnm.go
network.go
network_test.go
pkg/oci/utils.go
qemu.go

This patch change the default internetwork model based in the pod
configuration.
Fixes: #527
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

network: pod: Get default internetwork model from pod configuration

---

container.go
shim.go

Using force kill when we want to stop a container should only be
called after we left some time to make sure nothing has been killing
the container process. Indeed, signals can sometime take a few seconds
to terminate a process. In this case, we don't want to SIGKILL this
process, otherwise it would return with the exit code 137. Instead, we
want to leave it some time (10 seconds) so that it can properly end.
After those 10 seconds, we consider the previous signal didn't get the
expected effect and we force kill the container process. Indeed, we
still want to try to kill the container.
Fixes #606
Depends-on: github.com/clearcontainers/runtime#1003

container: Let some time before to force kill a container process

---

shim.go

Now, the container pid that is get by docker inspect -f '{{.State.Pid}}' [container_id] is the pid of shim process, and the shim process is in the host netwok namespace.
In some case, we should get the netwok namespace of container via the container pid (e.g. dockershim),
This PR moves the shim process into the pod network namespace like VM procewss.
Fixes #615
Related to https://github.com/clearcontainers/runtime/issues/987#issuecomment-364452318
/cc @sboeuf @sameo @plutoinmii
Signed-off-by: Yanqiang Miao <miao.yanqiang@zte.com.cn>

Run cc-shim in the network namespace of pod

---

kata_agent.go

This pull request enables CRI-O to work with Kata Containers in case the storage driver used is overlay, meaning we rely on 9pfs to pass the rootfs inside the VM.

kata_agent: Support CRI-O with overlay

---

Gopkg.lock
Gopkg.toml
vendor/github.com/intel/govmm/qemu/qemu.go
vendor/github.com/intel/govmm/qemu/qmp.go

This will add the support for machine options.
693d954 qemu: add options for the machine type
3273aaf scsi: Add function to send device_add qmp command for a scsi device
6d198b8 Compute coverage statistics for unit tests in Travis builds
3a31da3 scsi: Add a scsi controller device
Fixes #624
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

vendor: Re-vendor govmm

---

api.go
hyperstart_agent.go
pod.go
shim.go

We don't want to fetch the pod network from the filesystem every
time we need information about it. Instead, the network is related
to the pod, that's why the pod should hold this information in-memory
through a new field into its structure.
Fixes #628

pod: Fetch pod network only from createPod()

---

api.go
bridge.go
bridge_test.go
hypervisor.go
mock_hypervisor.go
qemu.go
qemu_amd64.go
qemu_amd64_test.go
qemu_arch_base.go
qemu_arch_base_test.go
qemu_arm64.go
qemu_test.go

This patch introduces a new interface called qemuArch that contains
the functions needed to create qemu specific architecture implementations.
This patch also includes three qemu specific architecture
implementations: qemuArchBase, qemuAmd64 and qemuArm64, since all architectures
use similar qemu command lines, the base structure is qemuArchBase that is an
agnostic implementation to start virtual machines, qemuAmd64 and qemuArm64
inherit and override (if needed) the functions of qemuArchBase, therefore architecture
specific optimizations are in qemuAmd64 and qemuArm64.
For example the `appendImage` function defined by qemuArchBase uses a block
device to provide the image to the VM, qemuArm64 inherits and doesn't
overwrite it, but qemuAmd64 inherits and overwites it to provide the
image …

qemu: Add support for ARM

---

documentation/api/1.0/api.md

The virtcontainers godoc [1] does not highlight the 1.0 top level API
in a readable and clear way. This API documentation attempts to
provide a top to bottom description of the virtcontainers 1.0 API.
[1] https://godoc.org/github.com/containers/virtcontainers

documentation: Document the 1.0 API

---

container.go

This configuration was added to disable block devices from being
used and using 9p instead. This got dropped somewhere, add it back.

block: Fix disabling block device use

---

NEWS

Added ARM64 support
Added Kata Containers support
Added dockershim support
Added govmm support
Added support for the one proxy per VM model
Added 1.0 API documentation
Added hotplug support for QEMU's Q35 machine type
Fixed the agent, proxy and shim hierarchy
Fixed the state storage implementation
Shortlog:
10d462c block: Fix disabling block device use
5236b92 documentation: Add API usage example
77c41ca documentation: Add short container 1.0 API description
0fbae82 documentation: Add short pod 1.0 API description
5a2d207 documentation: Document the 1.0 API
1ccb3a4 pod: Fetch pod network only from createPod()
563c175 qemu: change function names
d8a6dd3 qemu: update qemu init
b877182 qemu: add support for ARM
485b51b hypervisor: remove getState function
13d23e2 vendor: Re-vendor govmm …

1.0.7 release

---

api_test.go
container.go
device.go
device_test.go
hyperstart_agent.go
hypervisor.go
hypervisor_test.go
mount.go
mount_test.go
pkg/hyperstart/types.go
pod.go
qemu.go
qemu_arch_base.go
qemu_test.go

With this PR, block devices are hotplugged using either virtio-scsi or virtio-block based on a configuration.

Add support for scsi for hotplugging block devices

---

utils/virtcontainers-setup.sh

The #!/bin/bash was not on the first line.
Fixes: #640 
Signed-off-by: Graham whaley <graham.whaley@intel.com>

setup: #!/bin/bash in the wrong place

---

Gopkg.lock
Gopkg.toml
kata_agent.go
kata_agent_test.go
vendor/github.com/kata-containers/agent/protocols/client/client.go
vendor/github.com/kata-containers/agent/protocols/grpc/agent.pb.go
vendor/github.com/kata-containers/agent/protocols/grpc/health.pb.go
vendor/github.com/kata-containers/agent/protocols/grpc/oci.pb.go
vendor/github.com/kata-containers/agent/protocols/grpc/utils.go
vendor/github.com/kata-containers/agent/protocols/grpc/version.go

Introduce support for setting up interface and routes when working with
Kata agent.
Signed-off-by: Eric Ernst <eric.ernst@intel.com>

kata-agent: add network gRPC support

---

qemu.go

We were not checking the return err from addDeviceToBridge, which
can validly error out. lint/ineffassign picked this up.
Let's check the error return then...
Fixes: #650
Signed-off-by: Graham whaley <graham.whaley@intel.com>

check: lint: ineffassign in qemu.go

---

README.md
documentation/Developers.md
utils/virtcontainers-setup.sh

There was little info n how to get started with a build/install/run of virtcontainers.
Add some minimal introductory docs.

doc: developer: add some introductory developer docs

---

hyperstart_agent.go
kata_agent.go
pkg/nsenter/nsenter.go
pkg/nsenter/nsenter_test.go
shim.go

This PR first creates a new package `nsenter` so that we can spawn any code into a set of namespaces. Then, the virtcontainers code is modified to rely on this new package. At last, it starts shims from agents within the right PID namespace. In details, a shim representing a container process should enter its own PID namespace so that we can spawn other shims corresponding to exec'ed processes inside the same namespace. This is needed if we don't want some race conditions to happen, due to the exec'ed shims to never return their exit codes if the container process returned first.
Fixes #613

shim: Start shims inside appropriate namespaces

---

filesystem.go
filesystem_test.go

Some of the filesystem pod data tree (/var/lib/virtcontainers/*)
is currently created with the permission 01000 (d---------). This
looks like we have forgotten to or in the dirMode bits into
the MkdirAll() calls.
Or in the appropriate bits.
Fixes: #638
Signed-off-by: Graham whaley <graham.whaley@intel.com>

filesystem: set correct access mode for pod dir tree

---

api_test.go
container.go
container_test.go
hyperstart_agent.go
hypervisor.go
hypervisor_test.go
pkg/hyperstart/types.go
pkg/oci/utils.go
qemu.go
qemu_amd64.go
qemu_arch_base.go
qemu_arch_base_test.go
qemu_arm64.go
qemu_test.go
utils.go
utils_test.go

For hot-add, we have to know what CPUs are available using
`query-hotpluggable-cpus`.
For hot-remove we only need to know the CPUs ids in order to avoid the
use of 1 query 1 cpu, hotplugAddCPUs and hotRemoveCPUs receive the
total amount of CPUs to hot add or hot remove.
depending of the container's state, pod's resources are updated.
for example, if the container has a CPU constraint of 4 vCPU and it is stopped,
then these 4 vCPUs are removed.
another example, if the container is ready to be started and it has a CPU
constraint of 3 vCPUs, 3 vCPUs are added and the constraint is sent to the
agent to limit CPU usage of the container.
With this patch the fractional part of the CPU constraint is also honoured,
for example, if the container has a CPU constraint of 5.5, then 6 vCPUs are
added …

Add support for CPU hot add/remove

---

.gitignore
api_test.go
pkg/cni/cni_test.go
utils/virtcontainers-setup.sh

Rather than have some of our required test support files live in `/tmp`,
let's install them in a local dir instead.

test: move required test support files locally

---

Gopkg.lock
Gopkg.toml
qemu_arch_base.go
qemu_arch_base_test.go
vendor/github.com/intel/govmm/qemu/qemu.go

Disable modern to prevent qemu from relying on fast MMIO.
This change is needed to avoid boot issues when using virtio-scsi in a
nested virtual machine scenario.
fixes #663

qemu: disable modern in SCSI constroller

---

example_pod_run_test.go
hack/virtc/main.go
hypervisor.go
pkg/oci/utils.go
pkg/oci/utils_test.go
pod.go
qemu.go
qemu_test.go

Currently when a container with CPU constrains is created using docker,
the VM starts with a wrong number of vCPUs, the VM must start with the
number of vCPUs specified by `default_vcpus` allowing to the runtime hot
add/remove resources as needed.
For example if DefaultVCPUs (default_vcpus) is 1 and the container has
a constraint of 4 (docker run --cpus 4 ...), the VM must start with 1
vCPU because the runtime hot add 4 vCPUs.
Qemu command line example:
old:
`qemu-system-x86_64 ... -smp 4,cores=1,threads=1,sockets=1,maxcpus=240`
new:
`qemu-system-x86_64 ... -smp 1,cores=1,threads=1,sockets=1,maxcpus=240`
Depends-on: github.com/clearcontainers/runtime#1048
see clearcontainers/runtime#1032 and
clearcontainers/runtime#1041
fixes #661

qemu: honor DefaultVCPUs

---

container.go
hyperstart_agent.go
pkg/hyperstart/types.go
pkg/oci/utils.go

this patch is to apply CPU share constraint to new containers
fixes #669

oci: apply CPU share constraint

---

hyperstart_agent.go
kata_agent.go

We ignore routes that have an ipv6 destination, since we do not have support for ipv6 currently. We should do the same for default route that has an ipv6 gateway address.

Ignore route with ipv6 gateway
